(in-package #:iup)

(defun get-all-classes ()
  (let* ((max-n (iup-cffi::%iup-get-all-classes (cffi:null-pointer) 0))
	 (array (cffi:foreign-alloc :pointer :initial-element (cffi:null-pointer) :count max-n :null-terminated-p t)))
    (unwind-protect
	 (progn
	   (iup-cffi::%iup-get-all-classes array max-n)
	   (loop for i below max-n
		 for ref = (cffi:mem-aref array :pointer i)
		 until (cffi:null-pointer-p ref)
		 collect (cffi:foreign-string-to-lisp ref)))
      (cffi:foreign-free array))))

(defun get-classname-names (classname name-producer)
  (let* ((max-n (funcall name-producer classname (cffi:null-pointer) 0))
	 (array (cffi:foreign-alloc :pointer :initial-element (cffi:null-pointer) :count max-n :null-terminated-p t)))
    (unwind-protect
	 (progn
	   (funcall name-producer classname array max-n)
	   (loop for i below max-n
		 for ref = (cffi:mem-aref array :pointer i)
		 until (cffi:null-pointer-p ref)
		 collect (make-keyword (cffi:foreign-string-to-lisp ref))))
      (foreign-free array))))

(defun get-class-attributes (classname)
  (get-classname-names classname #'iup-cffi::%iup-get-class-attributes))

(defun get-class-callbacks (classname)
  (get-classname-names classname #'iup-cffi::%iup-get-class-callbacks))

;;; experimental

#|
(defun build-class-db (pathname)
  (with-open-file (stream pathname :direction :output :if-exists :supersede)
    (write 
     (with-iup
       (iup-scintilla:scintilla)
       (mapcar #'(lambda (classname)
		   (cl:list :classname classname
			    :attributes (get-class-attributes classname)
			    :callbacks (get-class-attributes classname)))
	       (get-all-classes)))
     :stream stream
     :pretty t
     :right-margin 80))
  (values))

#+linux
(defvar *class-db*
  '((:CLASSNAME "fill" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
		:NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
      :FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
		:NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
      :FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION))
    (:CLASSNAME "detachbox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :OLDBROTHER_HANDLE :BARSIZE :EXPANDWEIGHT
      :MAXSIZE :ACTIVE :RESTOREWHENCLOSED :NATURALSIZE :OLDPARENT_HANDLE :VISIBLE
      :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :DETACH :FONT :NAME :RESTORE :EXPAND
		:CANFOCUS :RASTERSIZE :COLOR :FLOATING :ORIENTATION :SHOWGRIP :WID
      :PANGOLAYOUT :XFONTID :MINSIZE :POSITION :CLIENTSIZE)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :OLDBROTHER_HANDLE :BARSIZE :EXPANDWEIGHT
      :MAXSIZE :ACTIVE :RESTOREWHENCLOSED :NATURALSIZE :OLDPARENT_HANDLE :VISIBLE
      :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :DETACH :FONT :NAME :RESTORE :EXPAND
		:CANFOCUS :RASTERSIZE :COLOR :FLOATING :ORIENTATION :SHOWGRIP :WID
      :PANGOLAYOUT :XFONTID :MINSIZE :POSITION :CLIENTSIZE))
    (:CLASSNAME "split" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :BARSIZE :EXPANDWEIGHT :MAXSIZE :MINMAX
		:ACTIVE :NATURALSIZE :VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS
		:CHARSIZE :HANDLENAME :SIZE :NORMALIZERGROUP :PANGOFONTDESC :LAYOUTDRAG
		:FONT :NAME :VALUE :EXPAND :CANFOCUS :AUTOHIDE :RASTERSIZE :COLOR :FLOATING
      :ORIENTATION :SHOWGRIP :WID :PANGOLAYOUT :DIRECTION :XFONTID :MINSIZE
		:POSITION :CLIENTSIZE)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :BARSIZE :EXPANDWEIGHT :MAXSIZE :MINMAX
		:ACTIVE :NATURALSIZE :VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS
		:CHARSIZE :HANDLENAME :SIZE :NORMALIZERGROUP :PANGOFONTDESC :LAYOUTDRAG
		:FONT :NAME :VALUE :EXPAND :CANFOCUS :AUTOHIDE :RASTERSIZE :COLOR :FLOATING
      :ORIENTATION :SHOWGRIP :WID :PANGOLAYOUT :DIRECTION :XFONTID :MINSIZE
		:POSITION :CLIENTSIZE))
    (:CLASSNAME "hbox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MARGIN :MAXSIZE :NORMALIZESIZE
		:NGAP :ACTIVE :EXPANDCHILDREN :GAP :CMARGIN :NATURALSIZE :VISIBLE
      :HOMOGENEOUS :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME
      :SIZE :NORMALIZERGROUP :PANGOFONTDESC :CGAP :FONT :NAME :NMARGIN :NCMARGIN
      :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :NCGAP :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MARGIN :MAXSIZE :NORMALIZESIZE
		:NGAP :ACTIVE :EXPANDCHILDREN :GAP :CMARGIN :NATURALSIZE :VISIBLE
      :HOMOGENEOUS :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME
      :SIZE :NORMALIZERGROUP :PANGOFONTDESC :CGAP :FONT :NAME :NMARGIN :NCMARGIN
      :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :NCGAP :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT))
    (:CLASSNAME "label" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :WORDWRAP :TIPICON :MAXSIZE :SCREENPOSITION
	       :POSITION :IMINACTIVE :DROPFILESTARGET :TIP :CANFOCUS :DRAGSOURCEMOVE
	       :VISIBLE :SEPARATOR :IMAGE :ZORDER :X :Y :DRAGDROP :EXPAND :SIZE :PADDING
	       :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :TITLE
	       :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :ALIGNMENT
	       :DRAGSOURCE :MARKUP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE
	       :TIPRECT :TIPFGCOLOR :FONTFACE :NAME :ELLIPSIS :ACTIVE :TIPVISIBLE
      :EXPANDWEIGHT :MINSIZE :CHARSIZE :DRAGTYPES :FONTSTYLE :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :WORDWRAP :TIPICON :MAXSIZE :SCREENPOSITION
	       :POSITION :IMINACTIVE :DROPFILESTARGET :TIP :CANFOCUS :DRAGSOURCEMOVE
	       :VISIBLE :SEPARATOR :IMAGE :ZORDER :X :Y :DRAGDROP :EXPAND :SIZE :PADDING
	       :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :TITLE
	       :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :ALIGNMENT
	       :DRAGSOURCE :MARKUP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE
	       :TIPRECT :TIPFGCOLOR :FONTFACE :NAME :ELLIPSIS :ACTIVE :TIPVISIBLE
      :EXPANDWEIGHT :MINSIZE :CHARSIZE :DRAGTYPES :FONTSTYLE :FONT))
    (:CLASSNAME "tree" :ATTRIBUTES
     (:COUNT :FGCOLOR :HANDLENAME :ADDEXPANDED :TIPBGCOLOR :DROPEQUALDRAG :KIND
	     :TIPICON :ADDLEAF :MAXSIZE :STARTING :SCREENPOSITION :IMAGEEXPANDED
	     :POSITION :INSERTLEAF :NEXT :DROPFILESTARGET :DRAGDROPTREE :TIP :CANFOCUS
      :DRAGSOURCEMOVE :VISIBLE :IMAGE :MOVENODE :ZORDER :X :Y :MARKED :DRAGDROP
	     :TITLEFONTSTYLE :TOGGLEVISIBLE :PREVIOUS :EXPAND :SIZE :SHIFT :TITLEFONTSIZE
      :WID :SHOWTOGGLE :TIPMARKUP :IMAGELEAF :DELNODE :TOPITEM :FONTSIZE :USERDATA
      :NATURALSIZE :CTRL :DROPTYPES :USERSIZE :TIPDELAY :TITLE :SHOWDRAGDROP
	     :EXPANDALL :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET
	     :DRAGSOURCE :FLOATING :COLOR :NORMALIZERGROUP :PANGOLAYOUT :SPACING
	     :RASTERSIZE :TIPRECT :TIPFGCOLOR :LASTADDNODE :LAST :DEPTH :FIRST :TITLEFONT
	     :MARKMODE :INSERTBRANCH :MARKWHENTOGGLE :FONTFACE :NAME :STATE :MARKSTART
      :VALUE :INDENTATION :ACTIVE :TIPVISIBLE :IMAGEBRANCHEXPANDED :EXPANDWEIGHT
      :MINSIZE :PARENT :MARK :ROOTCOUNT :TOGGLEVALUE :TOTALCHILDCOUNT :SHOWRENAME
	     :CHARSIZE :IMAGEBRANCHCOLLAPSED :DRAGTYPES :CHILDCOUNT :RENAME :MARKEDNODES
	     :FONTSTYLE :ADDROOT :ADDBRANCH :RUBBERBAND :COPYNODE :FONT)
     :CALLBACKS
     (:COUNT :FGCOLOR :HANDLENAME :ADDEXPANDED :TIPBGCOLOR :DROPEQUALDRAG :KIND
	     :TIPICON :ADDLEAF :MAXSIZE :STARTING :SCREENPOSITION :IMAGEEXPANDED
	     :POSITION :INSERTLEAF :NEXT :DROPFILESTARGET :DRAGDROPTREE :TIP :CANFOCUS
      :DRAGSOURCEMOVE :VISIBLE :IMAGE :MOVENODE :ZORDER :X :Y :MARKED :DRAGDROP
	     :TITLEFONTSTYLE :TOGGLEVISIBLE :PREVIOUS :EXPAND :SIZE :SHIFT :TITLEFONTSIZE
      :WID :SHOWTOGGLE :TIPMARKUP :IMAGELEAF :DELNODE :TOPITEM :FONTSIZE :USERDATA
      :NATURALSIZE :CTRL :DROPTYPES :USERSIZE :TIPDELAY :TITLE :SHOWDRAGDROP
	     :EXPANDALL :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET
	     :DRAGSOURCE :FLOATING :COLOR :NORMALIZERGROUP :PANGOLAYOUT :SPACING
	     :RASTERSIZE :TIPRECT :TIPFGCOLOR :LASTADDNODE :LAST :DEPTH :FIRST :TITLEFONT
	     :MARKMODE :INSERTBRANCH :MARKWHENTOGGLE :FONTFACE :NAME :STATE :MARKSTART
      :VALUE :INDENTATION :ACTIVE :TIPVISIBLE :IMAGEBRANCHEXPANDED :EXPANDWEIGHT
      :MINSIZE :PARENT :MARK :ROOTCOUNT :TOGGLEVALUE :TOTALCHILDCOUNT :SHOWRENAME
	     :CHARSIZE :IMAGEBRANCHCOLLAPSED :DRAGTYPES :CHILDCOUNT :RENAME :MARKEDNODES
	     :FONTSTYLE :ADDROOT :ADDBRANCH :RUBBERBAND :COPYNODE :FONT))
    (:CLASSNAME "backgroundbox" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :DECORATION :XMIN :TIPICON
		  :MAXSIZE :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET
      :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE
		  :VISIBLE :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP
      :CHILDOFFSET :EXPAND :DRAWFONT :SIZE :POSX :POSY :WID :TIPMARKUP :YMIN
		  :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
		  :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
      :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE
		  :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :DECOROFFSET
      :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE :FONTFACE :DRAWCOLOR
		  :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
		  :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :DECORSIZE :EXPANDWEIGHT :MINSIZE
      :BORDER :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :FONTSTYLE :TOUCH
		  :XDISPLAY :FONT)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :DECORATION :XMIN :TIPICON
		  :MAXSIZE :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET
      :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE
		  :VISIBLE :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP
      :CHILDOFFSET :EXPAND :DRAWFONT :SIZE :POSX :POSY :WID :TIPMARKUP :YMIN
		  :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
		  :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
      :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE
		  :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :DECOROFFSET
      :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE :FONTFACE :DRAWCOLOR
		  :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
		  :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :DECORSIZE :EXPANDWEIGHT :MINSIZE
      :BORDER :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :FONTSTYLE :TOUCH
		  :XDISPLAY :FONT))
    (:CLASSNAME "normalizer" :ATTRIBUTES
     (:DELCONTROL :ADDCONTROL_HANDLE :NORMALIZE :DELCONTROL_HANDLE :ADDCONTROL)
     :CALLBACKS
     (:DELCONTROL :ADDCONTROL_HANDLE :NORMALIZE :DELCONTROL_HANDLE :ADDCONTROL))
    (:CLASSNAME "fontdlg" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP :DIALOGHINT
      :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND :SIZE :WID :STATUS
      :TIPMARKUP :MDIMENU :STARTFOCUS :FONTSIZE :PREVIEWTEXT :NATURALSIZE
      :DROPTYPES :USERSIZE :TIPDELAY :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT
		  :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DRAGSOURCE
		  :RESIZE :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
		  :TIPFGCOLOR :FONTFACE :TOPMOST :NAME :MINBOX :DEFAULTENTER :MODAL
      :PARENTDIALOG :BACKGROUND :HIDETASKBAR :VALUE :BRINGFRONT :ACTIVE
      :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW :BORDER :SHRINK :CHARSIZE
		  :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE :MDICHILD
      :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP :DIALOGHINT
      :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND :SIZE :WID :STATUS
      :TIPMARKUP :MDIMENU :STARTFOCUS :FONTSIZE :PREVIEWTEXT :NATURALSIZE
      :DROPTYPES :USERSIZE :TIPDELAY :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT
		  :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DRAGSOURCE
		  :RESIZE :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
		  :TIPFGCOLOR :FONTFACE :TOPMOST :NAME :MINBOX :DEFAULTENTER :MODAL
      :PARENTDIALOG :BACKGROUND :HIDETASKBAR :VALUE :BRINGFRONT :ACTIVE
      :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW :BORDER :SHRINK :CHARSIZE
		  :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE :MDICHILD
      :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL))
    (:CLASSNAME "animatedlabel" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :WORDWRAP :FRAMETIME :TIPICON :MAXSIZE
	       :SCREENPOSITION :POSITION :FRAMECOUNT :IMINACTIVE :RUNNING :DROPFILESTARGET
	       :TIP :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :SEPARATOR :IMAGE :ZORDER :X :Y
      :DRAGDROP :EXPAND :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE :NATURALSIZE
      :DROPTYPES :USERSIZE :TIPDELAY :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID
	       :PANGOFONTDESC :DROPTARGET :ALIGNMENT :DRAGSOURCE :MARKUP :FLOATING
	       :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :START :TIPFGCOLOR
	       :FONTFACE :NAME :ELLIPSIS :ACTIVE :TIPVISIBLE :ANIMATION_HANDLE
	       :EXPANDWEIGHT :MINSIZE :ANIMATION :CHARSIZE :STOP :DRAGTYPES :STOPWHENHIDDEN
      :FONTSTYLE :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :WORDWRAP :FRAMETIME :TIPICON :MAXSIZE
	       :SCREENPOSITION :POSITION :FRAMECOUNT :IMINACTIVE :RUNNING :DROPFILESTARGET
	       :TIP :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :SEPARATOR :IMAGE :ZORDER :X :Y
      :DRAGDROP :EXPAND :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE :NATURALSIZE
      :DROPTYPES :USERSIZE :TIPDELAY :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID
	       :PANGOFONTDESC :DROPTARGET :ALIGNMENT :DRAGSOURCE :MARKUP :FLOATING
	       :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :START :TIPFGCOLOR
	       :FONTFACE :NAME :ELLIPSIS :ACTIVE :TIPVISIBLE :ANIMATION_HANDLE
	       :EXPANDWEIGHT :MINSIZE :ANIMATION :CHARSIZE :STOP :DRAGTYPES :STOPWHENHIDDEN
      :FONTSTYLE :FONT))
    (:CLASSNAME "colordlg" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :ZORDER :SHOWHELP :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP
      :DIALOGHINT :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND :SIZE :WID
      :STATUS :TIPMARKUP :MDIMENU :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES
		  :USERSIZE :TIPDELAY :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT
		  :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :COLORTABLE
		  :DRAGSOURCE :RESIZE :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE
		  :ALPHA :TIPRECT :TIPFGCOLOR :SHOWALPHA :FONTFACE :TOPMOST :NAME :MINBOX
		  :DEFAULTENTER :MODAL :PARENTDIALOG :BACKGROUND :HIDETASKBAR :VALUE
		  :BRINGFRONT :VALUEHEX :ACTIVE :TIPVISIBLE :SHOWCOLORTABLE :EXPANDWEIGHT
		  :MINSIZE :ACTIVEWINDOW :VALUEHSI :SHOWHEX :BORDER :SHRINK :CHARSIZE
      :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE :MDICHILD
		  :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :ZORDER :SHOWHELP :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP
      :DIALOGHINT :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND :SIZE :WID
      :STATUS :TIPMARKUP :MDIMENU :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES
		  :USERSIZE :TIPDELAY :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT
		  :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :COLORTABLE
		  :DRAGSOURCE :RESIZE :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE
		  :ALPHA :TIPRECT :TIPFGCOLOR :SHOWALPHA :FONTFACE :TOPMOST :NAME :MINBOX
		  :DEFAULTENTER :MODAL :PARENTDIALOG :BACKGROUND :HIDETASKBAR :VALUE
		  :BRINGFRONT :VALUEHEX :ACTIVE :TIPVISIBLE :SHOWCOLORTABLE :EXPANDWEIGHT
		  :MINSIZE :ACTIVEWINDOW :VALUEHSI :SHOWHEX :BORDER :SHRINK :CHARSIZE
      :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE :MDICHILD
		  :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL))
    (:CLASSNAME "timer" :ATTRIBUTES (:RUN :TIME :WID) :CALLBACKS
     (:RUN :TIME :WID))
    (:CLASSNAME "vbox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MARGIN :MAXSIZE :NORMALIZESIZE
		:NGAP :ACTIVE :EXPANDCHILDREN :GAP :CMARGIN :NATURALSIZE :VISIBLE
      :HOMOGENEOUS :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME
      :SIZE :NORMALIZERGROUP :PANGOFONTDESC :CGAP :FONT :NAME :NMARGIN :NCMARGIN
      :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :NCGAP :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MARGIN :MAXSIZE :NORMALIZESIZE
		:NGAP :ACTIVE :EXPANDCHILDREN :GAP :CMARGIN :NATURALSIZE :VISIBLE
      :HOMOGENEOUS :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME
      :SIZE :NORMALIZERGROUP :PANGOFONTDESC :CGAP :FONT :NAME :NMARGIN :NCMARGIN
      :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :NCGAP :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT))
    (:CLASSNAME "tabs" :ATTRIBUTES
     (:COUNT :FGCOLOR :HANDLENAME :TIPBGCOLOR :TIPICON :MAXSIZE :SCREENPOSITION
	     :POSITION :TIP :SHOWCLOSE :CANFOCUS :VISIBLE :ZORDER :X :Y :CHILDOFFSET
      :TABTYPE :EXPAND :SIZE :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :USERSIZE
      :TIPDELAY :TABVISIBLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :VALUE_HANDLE
      :PANGOFONTDESC :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
      :TIPFGCOLOR :FONTFACE :TABORIENTATION :NAME :VALUEPOS :VALUE :TABIMAGE
	     :MULTILINE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :CHARSIZE :CLIENTSIZE
      :CLIENTOFFSET :FONTSTYLE :TABPADDING :TABTITLE :FONT)
     :CALLBACKS
     (:COUNT :FGCOLOR :HANDLENAME :TIPBGCOLOR :TIPICON :MAXSIZE :SCREENPOSITION
	     :POSITION :TIP :SHOWCLOSE :CANFOCUS :VISIBLE :ZORDER :X :Y :CHILDOFFSET
      :TABTYPE :EXPAND :SIZE :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :USERSIZE
      :TIPDELAY :TABVISIBLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :VALUE_HANDLE
      :PANGOFONTDESC :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
      :TIPFGCOLOR :FONTFACE :TABORIENTATION :NAME :VALUEPOS :VALUE :TABIMAGE
	     :MULTILINE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :CHARSIZE :CLIENTSIZE
      :CLIENTOFFSET :FONTSTYLE :TABPADDING :TABTITLE :FONT))
    (:CLASSNAME "multiline" :ATTRIBUTES
     (:FGCOLOR :COUNT :HANDLENAME :TIPBGCOLOR :WORDWRAP :PASSWORD :CARET
	       :MASKDECIMALSYMBOL :TIPICON :OVERWRITE :ADDFORMATTAG_HANDLE :SPININC
      :MAXSIZE :SCREENPOSITION :POSITION :APPENDNEWLINE :DROPFILESTARGET :TIP
      :CANFOCUS :MASKFLOAT :DRAGSOURCEMOVE :ADDFORMATTAG :VISIBLE :NC :INSERT
	       :ZORDER :X :Y :DRAGDROP :MASKREAL :LINEVALUE :EXPAND :VISIBLELINES :SIZE
      :PADDING :SPINMIN :WID :SELECTION :TIPMARKUP :FONTSIZE :NATURALSIZE
	       :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :TABSIZE :PROPAGATEFOCUS :BGCOLOR
      :XFONTID :PANGOFONTDESC :DROPTARGET :VALUEMASKED :ALIGNMENT :DRAGSOURCE
      :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :SCROLLTOPOS :FORMATTING
      :SCROLLTO :TIPRECT :TIPFGCOLOR :LINECOUNT :SPINWRAP :FONTFACE
      :VISIBLECOLUMNS :MASKINT :SPINVALUE :SPINALIGN :NAME :MASKCASEI
      :SELECTIONPOS :VALUE :FILTER :SPINMAX :MULTILINE :SELECTEDTEXT :ACTIVE
	       :TIPVISIBLE :CUEBANNER :EXPANDWEIGHT :MINSIZE :SPIN :BORDER :CHARSIZE
      :CARETPOS :SPINAUTO :MASK :DRAGTYPES :AUTOHIDE :FONTSTYLE :CLIPBOARD
	       :REMOVEFORMATTING :READONLY :APPEND :MASKNOEMPTY :FONT)
     :CALLBACKS
     (:FGCOLOR :COUNT :HANDLENAME :TIPBGCOLOR :WORDWRAP :PASSWORD :CARET
	       :MASKDECIMALSYMBOL :TIPICON :OVERWRITE :ADDFORMATTAG_HANDLE :SPININC
      :MAXSIZE :SCREENPOSITION :POSITION :APPENDNEWLINE :DROPFILESTARGET :TIP
      :CANFOCUS :MASKFLOAT :DRAGSOURCEMOVE :ADDFORMATTAG :VISIBLE :NC :INSERT
	       :ZORDER :X :Y :DRAGDROP :MASKREAL :LINEVALUE :EXPAND :VISIBLELINES :SIZE
      :PADDING :SPINMIN :WID :SELECTION :TIPMARKUP :FONTSIZE :NATURALSIZE
	       :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :TABSIZE :PROPAGATEFOCUS :BGCOLOR
      :XFONTID :PANGOFONTDESC :DROPTARGET :VALUEMASKED :ALIGNMENT :DRAGSOURCE
      :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :SCROLLTOPOS :FORMATTING
      :SCROLLTO :TIPRECT :TIPFGCOLOR :LINECOUNT :SPINWRAP :FONTFACE
      :VISIBLECOLUMNS :MASKINT :SPINVALUE :SPINALIGN :NAME :MASKCASEI
      :SELECTIONPOS :VALUE :FILTER :SPINMAX :MULTILINE :SELECTEDTEXT :ACTIVE
	       :TIPVISIBLE :CUEBANNER :EXPANDWEIGHT :MINSIZE :SPIN :BORDER :CHARSIZE
      :CARETPOS :SPINAUTO :MASK :DRAGTYPES :AUTOHIDE :FONTSTYLE :CLIPBOARD
	       :REMOVEFORMATTING :READONLY :APPEND :MASKNOEMPTY :FONT))
    (:CLASSNAME "flatframe" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :DECORATION :XMIN :TIPICON
		  :MAXSIZE :DRAWTEXTWRAP :SCREENPOSITION :TITLEIMAGE :POSITION
      :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS
		  :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y
      :DRAGDROP :TITLETEXTORIENTATION :CHILDOFFSET :EXPAND :TITLETEXTCLIP
		  :DRAWFONT :SIZE :POSX :POSY :WID :FRAMESPACE :TIPMARKUP :YMIN
		  :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
		  :SCROLLBAR :XHIDDEN :TITLE :XAUTOHIDE :TITLECOLOR :TITLELINECOLOR
		  :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :TITLEIMAGEPOSITION :PANGOFONTDESC
		  :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP
      :FLOATING :TITLETEXTALIGNMENT :NORMALIZERGROUP :PANGOLAYOUT :DECOROFFSET
		  :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE :FRAMECOLOR :FONTFACE
      :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :TITLEIMAGESPACING :NAME
		  :BACKINGSTORE :DRAWDRIVER :TITLEBGCOLOR :YAUTOHIDE :DRAWSTYLE :ACTIVE
		  :TIPVISIBLE :YMAX :DECORSIZE :EXPANDWEIGHT :MINSIZE :TITLELINEWIDTH
		  :TITLETEXTELLIPSIS :BORDER :CHARSIZE :CLIENTSIZE :TITLEALIGNMENT
      :CLIENTOFFSET :DRAGTYPES :TITLETEXTWRAP :FONTSTYLE :TOUCH :TITLEPADDING
      :TITLELINE :FRAMEWIDTH :XDISPLAY :FRAME :FONT)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :DECORATION :XMIN :TIPICON
		  :MAXSIZE :DRAWTEXTWRAP :SCREENPOSITION :TITLEIMAGE :POSITION
      :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS
		  :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y
      :DRAGDROP :TITLETEXTORIENTATION :CHILDOFFSET :EXPAND :TITLETEXTCLIP
		  :DRAWFONT :SIZE :POSX :POSY :WID :FRAMESPACE :TIPMARKUP :YMIN
		  :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
		  :SCROLLBAR :XHIDDEN :TITLE :XAUTOHIDE :TITLECOLOR :TITLELINECOLOR
		  :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :TITLEIMAGEPOSITION :PANGOFONTDESC
		  :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP
      :FLOATING :TITLETEXTALIGNMENT :NORMALIZERGROUP :PANGOLAYOUT :DECOROFFSET
		  :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE :FRAMECOLOR :FONTFACE
      :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :TITLEIMAGESPACING :NAME
		  :BACKINGSTORE :DRAWDRIVER :TITLEBGCOLOR :YAUTOHIDE :DRAWSTYLE :ACTIVE
		  :TIPVISIBLE :YMAX :DECORSIZE :EXPANDWEIGHT :MINSIZE :TITLELINEWIDTH
		  :TITLETEXTELLIPSIS :BORDER :CHARSIZE :CLIENTSIZE :TITLEALIGNMENT
      :CLIENTOFFSET :DRAGTYPES :TITLETEXTWRAP :FONTSTYLE :TOUCH :TITLEPADDING
      :TITLELINE :FRAMEWIDTH :XDISPLAY :FRAME :FONT))
    (:CLASSNAME "image" :ATTRIBUTES
     (:RESIZE :SCALED :BPP :RESHAPE :CHANNELS :HOTSPOT :HEIGHT :CLEARCACHE
      :BGCOLOR :ORIGINALSCALE :WIDTH :RASTERSIZE :WID)
     :CALLBACKS
     (:RESIZE :SCALED :BPP :RESHAPE :CHANNELS :HOTSPOT :HEIGHT :CLEARCACHE
      :BGCOLOR :ORIGINALSCALE :WIDTH :RASTERSIZE :WID))
    (:CLASSNAME "dropbutton" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :HASFOCUS :FRONTIMAGEHIGHLIGHT
      :XMIN :TIPICON :MAXSIZE :ARROWIMAGEPRESS :DRAWTEXTWRAP :SCREENPOSITION
      :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER
	       :CANFOCUS :DRAGSOURCEMOVE :PSCOLOR :VISIBLE :DROPPOSITION :IMAGE
	       :ARROWPADDING :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP
      :EXPAND :DRAWFONT :SIZE :PADDING :POSX :POSY :WID :BORDERHLCOLOR :TIPMARKUP
	       :YMIN :TEXTCLIP :TEXTELLIPSIS :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE
	       :DROPTYPES :USERSIZE :TIPDELAY :BACKIMAGEINACTIVE :DROPCHILD :SCROLLBAR
	       :XHIDDEN :TITLE :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
      :PANGOFONTDESC :DROPTARGET :HIGHLIGHTED :DX :DY :DRAWABLE :ALIGNMENT
	       :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :SPACING :BORDERPSCOLOR :RASTERSIZE :BORDERCOLOR :ARROWSIZE
      :TIPRECT :TIPFGCOLOR :YHIDDEN :ARROWIMAGEHIGHLIGHT :FRONTIMAGEINACTIVE
	       :ARROWIMAGEINACTIVE :BACKIMAGEHIGHLIGHT :FRONTIMAGEPRESS :DRAWSIZE :HLCOLOR
      :FRONTIMAGE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR
	       :VISIBLECOLUMNS :IMAGEPRESS :NAME :ARROWIMAGE :BACKINGSTORE :DRAWDRIVER
	       :YAUTOHIDE :DRAWSTYLE :DROPCHILD_HANDLE :BACKIMAGEZOOM :TEXTORIENTATION
      :FITTOBACKIMAGE :ACTIVE :TIPVISIBLE :IMAGEHIGHLIGHT :YMAX :BACKIMAGE
      :IMAGEINACTIVE :DROPONARROW :SHOWDROPDOWN :EXPANDWEIGHT :MINSIZE :SHOWBORDER
      :ARROWIMAGES :BORDER :ARROWACTIVE :CHARSIZE :IMAGEPOSITION :DRAGTYPES
      :BORDERWIDTH :FONTSTYLE :TEXTALIGNMENT :TOUCH :TEXTWRAP :XDISPLAY
      :BACKIMAGEPRESS :FONT :ARROWCOLOR :PRESSED)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :HASFOCUS :FRONTIMAGEHIGHLIGHT
      :XMIN :TIPICON :MAXSIZE :ARROWIMAGEPRESS :DRAWTEXTWRAP :SCREENPOSITION
      :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER
	       :CANFOCUS :DRAGSOURCEMOVE :PSCOLOR :VISIBLE :DROPPOSITION :IMAGE
	       :ARROWPADDING :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP
      :EXPAND :DRAWFONT :SIZE :PADDING :POSX :POSY :WID :BORDERHLCOLOR :TIPMARKUP
	       :YMIN :TEXTCLIP :TEXTELLIPSIS :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE
	       :DROPTYPES :USERSIZE :TIPDELAY :BACKIMAGEINACTIVE :DROPCHILD :SCROLLBAR
	       :XHIDDEN :TITLE :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
      :PANGOFONTDESC :DROPTARGET :HIGHLIGHTED :DX :DY :DRAWABLE :ALIGNMENT
	       :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :SPACING :BORDERPSCOLOR :RASTERSIZE :BORDERCOLOR :ARROWSIZE
      :TIPRECT :TIPFGCOLOR :YHIDDEN :ARROWIMAGEHIGHLIGHT :FRONTIMAGEINACTIVE
	       :ARROWIMAGEINACTIVE :BACKIMAGEHIGHLIGHT :FRONTIMAGEPRESS :DRAWSIZE :HLCOLOR
      :FRONTIMAGE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR
	       :VISIBLECOLUMNS :IMAGEPRESS :NAME :ARROWIMAGE :BACKINGSTORE :DRAWDRIVER
	       :YAUTOHIDE :DRAWSTYLE :DROPCHILD_HANDLE :BACKIMAGEZOOM :TEXTORIENTATION
      :FITTOBACKIMAGE :ACTIVE :TIPVISIBLE :IMAGEHIGHLIGHT :YMAX :BACKIMAGE
      :IMAGEINACTIVE :DROPONARROW :SHOWDROPDOWN :EXPANDWEIGHT :MINSIZE :SHOWBORDER
      :ARROWIMAGES :BORDER :ARROWACTIVE :CHARSIZE :IMAGEPOSITION :DRAGTYPES
      :BORDERWIDTH :FONTSTYLE :TEXTALIGNMENT :TOUCH :TEXTWRAP :XDISPLAY
      :BACKIMAGEPRESS :FONT :ARROWCOLOR :PRESSED))
    (:CLASSNAME "space" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
		:NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
      :FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
		:NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
      :FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION))
    (:CLASSNAME "flatseparator" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP
		  :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP
      :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
      :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :POSX
      :POSY :WID :TIPMARKUP :YMIN :ORIENTATION :DRAWMAKEINACTIVE :FONTSIZE
		  :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
      :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
      :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING :COLOR
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN
      :STYLE :BARSIZE :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION
      :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE
		  :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :BORDER :CHARSIZE :DRAGTYPES
      :FONTSTYLE :TOUCH :XDISPLAY :FONT)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP
		  :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP
      :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
      :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :POSX
      :POSY :WID :TIPMARKUP :YMIN :ORIENTATION :DRAWMAKEINACTIVE :FONTSIZE
		  :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
      :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
      :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING :COLOR
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN
      :STYLE :BARSIZE :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION
      :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE
		  :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :BORDER :CHARSIZE :DRAGTYPES
      :FONTSTYLE :TOUCH :XDISPLAY :FONT))
    (:CLASSNAME "sbox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:COLOR :FLOATING :WID :PANGOLAYOUT :DIRECTION :XFONTID :MINSIZE :POSITION
		:CLIENTSIZE)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:COLOR :FLOATING :WID :PANGOLAYOUT :DIRECTION :XFONTID :MINSIZE :POSITION
		:CLIENTSIZE))
    (:CLASSNAME "flatlabel" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
	       :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :IMAGE :LINEX
	       :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT
      :SIZE :PADDING :POSX :POSY :WID :TIPMARKUP :YMIN :TEXTCLIP :TEXTELLIPSIS
	       :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
	       :BACKIMAGEINACTIVE :SCROLLBAR :XHIDDEN :TITLE :XAUTOHIDE :PROPAGATEFOCUS
	       :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE
	       :ALIGNMENT :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :SPACING :RASTERSIZE :TIPRECT :TIPFGCOLOR
      :YHIDDEN :FRONTIMAGEINACTIVE :DRAWSIZE :FRONTIMAGE :FONTFACE :DRAWCOLOR
      :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
      :DRAWSTYLE :BACKIMAGEZOOM :TEXTORIENTATION :FITTOBACKIMAGE :ACTIVE
	       :TIPVISIBLE :YMAX :BACKIMAGE :IMAGEINACTIVE :EXPANDWEIGHT :MINSIZE :BORDER
      :CHARSIZE :IMAGEPOSITION :DRAGTYPES :FONTSTYLE :TEXTALIGNMENT :TOUCH
      :TEXTWRAP :XDISPLAY :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
	       :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :IMAGE :LINEX
	       :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT
      :SIZE :PADDING :POSX :POSY :WID :TIPMARKUP :YMIN :TEXTCLIP :TEXTELLIPSIS
	       :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
	       :BACKIMAGEINACTIVE :SCROLLBAR :XHIDDEN :TITLE :XAUTOHIDE :PROPAGATEFOCUS
	       :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE
	       :ALIGNMENT :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :SPACING :RASTERSIZE :TIPRECT :TIPFGCOLOR
      :YHIDDEN :FRONTIMAGEINACTIVE :DRAWSIZE :FRONTIMAGE :FONTFACE :DRAWCOLOR
      :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
      :DRAWSTYLE :BACKIMAGEZOOM :TEXTORIENTATION :FITTOBACKIMAGE :ACTIVE
	       :TIPVISIBLE :YMAX :BACKIMAGE :IMAGEINACTIVE :EXPANDWEIGHT :MINSIZE :BORDER
      :CHARSIZE :IMAGEPOSITION :DRAGTYPES :FONTSTYLE :TEXTALIGNMENT :TOUCH
      :TEXTWRAP :XDISPLAY :FONT))
    (:CLASSNAME "param" :ATTRIBUTES
     (:INTERVAL :DIRECTORY :LABEL :NOOVERWRITEPROMPT :TITLE :PRECISION :PARTIAL
		:INDEX :MULTILINE :FILTER :TIP :MAX :NOFRAME :INDENT :CONTROL :BUTTON1
      :BUTTON2 :MASK :BUTTON3 :TRUE :ANGLE :TYPE :VALUE :FALSE :DIALOGTYPE
		:NOCHANGEDIR :AUXCONTROL :MIN :DATATYPE :STEP)
     :CALLBACKS
     (:INTERVAL :DIRECTORY :LABEL :NOOVERWRITEPROMPT :TITLE :PRECISION :PARTIAL
		:INDEX :MULTILINE :FILTER :TIP :MAX :NOFRAME :INDENT :CONTROL :BUTTON1
      :BUTTON2 :MASK :BUTTON3 :TRUE :ANGLE :TYPE :VALUE :FALSE :DIALOGTYPE
		:NOCHANGEDIR :AUXCONTROL :MIN :DATATYPE :STEP))
    (:CLASSNAME "button" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :TIPICON :MAXSIZE :SCREENPOSITION :POSITION
	       :IMPRESS :IMINACTIVE :TIP :CANFOCUS :VISIBLE :IMAGE :ZORDER :X :Y :EXPAND
	       :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :USERSIZE :TIPDELAY
	       :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :ALIGNMENT
	       :IMPRESSBORDER :MARKUP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :SPACING
	       :FOCUSONCLICK :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :NAME :ACTIVE
      :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :FLAT :CHARSIZE :IMAGEPOSITION :FONTSTYLE
	       :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :TIPICON :MAXSIZE :SCREENPOSITION :POSITION
	       :IMPRESS :IMINACTIVE :TIP :CANFOCUS :VISIBLE :IMAGE :ZORDER :X :Y :EXPAND
	       :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :USERSIZE :TIPDELAY
	       :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :ALIGNMENT
	       :IMPRESSBORDER :MARKUP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :SPACING
	       :FOCUSONCLICK :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :NAME :ACTIVE
      :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :FLAT :CHARSIZE :IMAGEPOSITION :FONTSTYLE
	       :FONT))
    (:CLASSNAME "filedlg" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :SHOWPREVIEW
		  :MENU :MAXSIZE :OPACITYIMAGE :NOCHANGEDIR :HELPBUTTON :SCREENPOSITION
		  :OPACITY :POSITION :COMPOSITED :DROPFILESTARGET :PREVIEWHEIGHT :BORDERSIZE
		  :TIP :CANFOCUS :MULTIPLEFILES :DRAGSOURCEMOVE :ICON :VISIBLE :PREVIEWWIDTH
      :CURSOR :MENUBOX :DIALOGTYPE :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP
		  :DIALOGHINT :ALLOWNEW :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND
      :SIZE :PREVIEWDC :WID :FILTERINFO :STATUS :TIPMARKUP :EXTDEFAULT :MDIMENU
      :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
      :CUSTOMFRAME :FILE :TITLE :DEFAULTESC :PLACEMENT :EXTFILTER :PROPAGATEFOCUS
		  :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DRAGSOURCE :RESIZE :FLOATING
      :MULTIVALUEPATH :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
		  :TIPFGCOLOR :FONTFACE :TOPMOST :NAME :MINBOX :DEFAULTENTER :MODAL
      :PARENTDIALOG :BACKGROUND :FILTERUSED :HIDETASKBAR :FILTER :VALUE
      :BRINGFRONT :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW
      :SHOWHIDDEN :FILEEXIST :BORDER :SHRINK :CHARSIZE :CLIENTSIZE :CLIENTOFFSET
		  :DRAGTYPES :TOOLBOX :MDIFRAME :NOOVERWRITEPROMPT :FONTSTYLE :DIRECTORY
		  :MDICHILD :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :SHOWPREVIEW
		  :MENU :MAXSIZE :OPACITYIMAGE :NOCHANGEDIR :HELPBUTTON :SCREENPOSITION
		  :OPACITY :POSITION :COMPOSITED :DROPFILESTARGET :PREVIEWHEIGHT :BORDERSIZE
		  :TIP :CANFOCUS :MULTIPLEFILES :DRAGSOURCEMOVE :ICON :VISIBLE :PREVIEWWIDTH
      :CURSOR :MENUBOX :DIALOGTYPE :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP
		  :DIALOGHINT :ALLOWNEW :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND
      :SIZE :PREVIEWDC :WID :FILTERINFO :STATUS :TIPMARKUP :EXTDEFAULT :MDIMENU
      :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
      :CUSTOMFRAME :FILE :TITLE :DEFAULTESC :PLACEMENT :EXTFILTER :PROPAGATEFOCUS
		  :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DRAGSOURCE :RESIZE :FLOATING
      :MULTIVALUEPATH :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
		  :TIPFGCOLOR :FONTFACE :TOPMOST :NAME :MINBOX :DEFAULTENTER :MODAL
      :PARENTDIALOG :BACKGROUND :FILTERUSED :HIDETASKBAR :FILTER :VALUE
      :BRINGFRONT :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW
      :SHOWHIDDEN :FILEEXIST :BORDER :SHRINK :CHARSIZE :CLIENTSIZE :CLIENTOFFSET
		  :DRAGTYPES :TOOLBOX :MDIFRAME :NOOVERWRITEPROMPT :FONTSTYLE :DIRECTORY
		  :MDICHILD :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL))
    (:CLASSNAME "list" :ATTRIBUTES
     (:COUNT :FGCOLOR :HANDLENAME :TIPBGCOLOR :CARET :MASKDECIMALSYMBOL :TIPICON
	     :VISIBLE_ITEMS :MAXSIZE :SCREENPOSITION :POSITION :DROPFILESTARGET :TIP
	     :CANFOCUS :MASKFLOAT :DRAGSOURCEMOVE :VISIBLE :IMAGE :NC :INSERT :ZORDER :X
      :Y :SHOWIMAGE :DRAGDROP :MASKREAL :EXPAND :VISIBLELINES :SIZE :PADDING
      :VALUESTRING :WID :DROPEXPAND :SELECTION :TIPMARKUP :DRAGDROPLIST
      :REMOVEITEM :TOPITEM :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
	     :VISIBLEITEMS :SCROLLBAR :SHOWDRAGDROP :PROPAGATEFOCUS :BGCOLOR :XFONTID
	     :PANGOFONTDESC :DROPTARGET :EDITBOX :VALUEMASKED :DRAGSOURCE :FLOATING
	     :NORMALIZERGROUP :PANGOLAYOUT :SPACING :INSERTITEM :RASTERSIZE :SCROLLTOPOS
	     :SCROLLTO :TIPRECT :TIPFGCOLOR :FONTFACE :VISIBLECOLUMNS :MASKINT
	     :APPENDITEM :NAME :MASKCASEI :MULTIPLE :SELECTIONPOS :VALUE :SELECTEDTEXT
      :ACTIVE :TIPVISIBLE :SHOWDROPDOWN :EXPANDWEIGHT :MINSIZE :IDVALUE :CHARSIZE
	     :CARETPOS :MASK :DRAGTYPES :AUTOHIDE :FONTSTYLE :AUTOREDRAW :CLIPBOARD
      :DROPDOWN :READONLY :APPEND :MASKNOEMPTY :FONT)
     :CALLBACKS
     (:COUNT :FGCOLOR :HANDLENAME :TIPBGCOLOR :CARET :MASKDECIMALSYMBOL :TIPICON
	     :VISIBLE_ITEMS :MAXSIZE :SCREENPOSITION :POSITION :DROPFILESTARGET :TIP
	     :CANFOCUS :MASKFLOAT :DRAGSOURCEMOVE :VISIBLE :IMAGE :NC :INSERT :ZORDER :X
      :Y :SHOWIMAGE :DRAGDROP :MASKREAL :EXPAND :VISIBLELINES :SIZE :PADDING
      :VALUESTRING :WID :DROPEXPAND :SELECTION :TIPMARKUP :DRAGDROPLIST
      :REMOVEITEM :TOPITEM :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
	     :VISIBLEITEMS :SCROLLBAR :SHOWDRAGDROP :PROPAGATEFOCUS :BGCOLOR :XFONTID
	     :PANGOFONTDESC :DROPTARGET :EDITBOX :VALUEMASKED :DRAGSOURCE :FLOATING
	     :NORMALIZERGROUP :PANGOLAYOUT :SPACING :INSERTITEM :RASTERSIZE :SCROLLTOPOS
	     :SCROLLTO :TIPRECT :TIPFGCOLOR :FONTFACE :VISIBLECOLUMNS :MASKINT
	     :APPENDITEM :NAME :MASKCASEI :MULTIPLE :SELECTIONPOS :VALUE :SELECTEDTEXT
      :ACTIVE :TIPVISIBLE :SHOWDROPDOWN :EXPANDWEIGHT :MINSIZE :IDVALUE :CHARSIZE
	     :CARETPOS :MASK :DRAGTYPES :AUTOHIDE :FONTSTYLE :AUTOREDRAW :CLIPBOARD
      :DROPDOWN :READONLY :APPEND :MASKNOEMPTY :FONT))
    (:CLASSNAME "zbox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :VALUEPOS :CHARSIZE
		:HANDLENAME :SIZE :VALUE_HANDLE :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME
      :VALUE :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :VALUEPOS :CHARSIZE
		:HANDLENAME :SIZE :VALUE_HANDLE :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME
      :VALUE :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT))
    (:CLASSNAME "scrollbox" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
		  :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
		  :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :SCROLLTOCHILD :CHILDOFFSET
		  :SCROLLTOCHILD_HANDLE :EXPAND :DRAWFONT :SIZE :POSX :POSY :WID :TIPMARKUP
		  :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE
		  :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR
      :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS
		  :DRAGSOURCE :DRAWTEXTCLIP :LAYOUTDRAG :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :RASTERSIZE :SCROLLTO :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE
		  :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE
		  :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT
      :MINSIZE :BORDER :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :FONTSTYLE
		  :TOUCH :XDISPLAY :FONT)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
		  :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
		  :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :SCROLLTOCHILD :CHILDOFFSET
		  :SCROLLTOCHILD_HANDLE :EXPAND :DRAWFONT :SIZE :POSX :POSY :WID :TIPMARKUP
		  :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE
		  :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR
      :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS
		  :DRAGSOURCE :DRAWTEXTCLIP :LAYOUTDRAG :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :RASTERSIZE :SCROLLTO :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE
		  :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE
		  :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT
      :MINSIZE :BORDER :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :FONTSTYLE
		  :TOUCH :XDISPLAY :FONT))
    (:CLASSNAME "datepick" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :TODAY :TIPICON :MAXSIZE :SCREENPOSITION
	       :POSITION :TIP :CANFOCUS :VISIBLE :SEPARATOR :ZORDER :X :Y :CHILDOFFSET
      :EXPAND :ZEROPRECED :SIZE :WID :TIPMARKUP :SUNKEN :FONTSIZE :NATURALSIZE
      :USERSIZE :TIPDELAY :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC
	       :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR
	       :FONTFACE :NAME :VALUE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :CHARSIZE
	       :CLIENTSIZE :CLIENTOFFSET :CALENDARWEEKNUMBERS :FONTSTYLE :ORDER :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :TODAY :TIPICON :MAXSIZE :SCREENPOSITION
	       :POSITION :TIP :CANFOCUS :VISIBLE :SEPARATOR :ZORDER :X :Y :CHILDOFFSET
      :EXPAND :ZEROPRECED :SIZE :WID :TIPMARKUP :SUNKEN :FONTSIZE :NATURALSIZE
      :USERSIZE :TIPDELAY :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC
	       :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR
	       :FONTFACE :NAME :VALUE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :CHARSIZE
	       :CLIENTSIZE :CLIENTOFFSET :CALENDARWEEKNUMBERS :FONTSTYLE :ORDER :FONT))
    (:CLASSNAME "spin" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MARGIN :MAXSIZE :NORMALIZESIZE
		:NGAP :ACTIVE :EXPANDCHILDREN :GAP :CMARGIN :NATURALSIZE :VISIBLE
      :HOMOGENEOUS :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME
      :SIZE :NORMALIZERGROUP :PANGOFONTDESC :CGAP :FONT :NAME :NMARGIN :NCMARGIN
      :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :NCGAP :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MARGIN :MAXSIZE :NORMALIZESIZE
		:NGAP :ACTIVE :EXPANDCHILDREN :GAP :CMARGIN :NATURALSIZE :VISIBLE
      :HOMOGENEOUS :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME
      :SIZE :NORMALIZERGROUP :PANGOFONTDESC :CGAP :FONT :NAME :NMARGIN :NCMARGIN
      :EXPAND :CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :NCGAP :XFONTID
      :MINSIZE :POSITION :CLIENTSIZE :ALIGNMENT))
    (:CLASSNAME "clipboard" :ATTRIBUTES
     (:FORMAT :TEXT :TEXTAVAILABLE :FORMATDATASIZE :IMAGE :ADDFORMAT
      :IMAGEAVAILABLE :FORMATDATA :FORMATAVAILABLE :NATIVEIMAGE)
     :CALLBACKS
     (:FORMAT :TEXT :TEXTAVAILABLE :FORMATDATASIZE :IMAGE :ADDFORMAT
      :IMAGEAVAILABLE :FORMATDATA :FORMATAVAILABLE :NATIVEIMAGE))
    (:CLASSNAME "submenu" :ATTRIBUTES
     (:ACTIVE :TITLE :IMAGE :BGCOLOR :KEY :FONT :NAME :WID) :CALLBACKS
     (:ACTIVE :TITLE :IMAGE :BGCOLOR :KEY :FONT :NAME :WID))
    (:CLASSNAME "gridbox" :ATTRIBUTES
     (:HANDLENAME :NORMALIZESIZE :GAPLIN :MAXSIZE :EXPANDCHILDREN :POSITION
      :CANFOCUS :ALIGNMENTCOL :VISIBLE :SIZECOL :CGAPCOL :CMARGIN :EXPAND
		  :ALIGNMENTLIN :SIZE :SIZELIN :WID :CGAPLIN :ORIENTATION :FONTSIZE
      :NATURALSIZE :USERSIZE :NGAPCOL :PROPAGATEFOCUS :XFONTID :PANGOFONTDESC
      :FLOATING :NMARGIN :NORMALIZERGROUP :PANGOLAYOUT :HOMOGENEOUSCOL :RASTERSIZE
      :NCGAPCOL :NGAPLIN :FONTFACE :HOMOGENEOUSLIN :NUMDIV :NCGAPLIN :NAME :NUMCOL
      :ACTIVE :EXPANDWEIGHT :MINSIZE :NUMLIN :CHARSIZE :CLIENTSIZE :CLIENTOFFSET
		  :FONTSTYLE :GAPCOL :FITTOCHILDREN :NCMARGIN :MARGIN :FONT)
     :CALLBACKS
     (:HANDLENAME :NORMALIZESIZE :GAPLIN :MAXSIZE :EXPANDCHILDREN :POSITION
      :CANFOCUS :ALIGNMENTCOL :VISIBLE :SIZECOL :CGAPCOL :CMARGIN :EXPAND
		  :ALIGNMENTLIN :SIZE :SIZELIN :WID :CGAPLIN :ORIENTATION :FONTSIZE
      :NATURALSIZE :USERSIZE :NGAPCOL :PROPAGATEFOCUS :XFONTID :PANGOFONTDESC
      :FLOATING :NMARGIN :NORMALIZERGROUP :PANGOLAYOUT :HOMOGENEOUSCOL :RASTERSIZE
      :NCGAPCOL :NGAPLIN :FONTFACE :HOMOGENEOUSLIN :NUMDIV :NCGAPLIN :NAME :NUMCOL
      :ACTIVE :EXPANDWEIGHT :MINSIZE :NUMLIN :CHARSIZE :CLIENTSIZE :CLIENTOFFSET
		  :FONTSTYLE :GAPCOL :FITTOCHILDREN :NCMARGIN :MARGIN :FONT))
    (:CLASSNAME "imagergba" :ATTRIBUTES
     (:RESIZE :SCALED :BPP :RESHAPE :CHANNELS :HOTSPOT :HEIGHT :CLEARCACHE
      :BGCOLOR :ORIGINALSCALE :WIDTH :RASTERSIZE :WID)
     :CALLBACKS
     (:RESIZE :SCALED :BPP :RESHAPE :CHANNELS :HOTSPOT :HEIGHT :CLEARCACHE
      :BGCOLOR :ORIGINALSCALE :WIDTH :RASTERSIZE :WID))
    (:CLASSNAME "text" :ATTRIBUTES
     (:FGCOLOR :COUNT :HANDLENAME :TIPBGCOLOR :WORDWRAP :PASSWORD :CARET
	       :MASKDECIMALSYMBOL :TIPICON :OVERWRITE :ADDFORMATTAG_HANDLE :SPININC
      :MAXSIZE :SCREENPOSITION :POSITION :APPENDNEWLINE :DROPFILESTARGET :TIP
      :CANFOCUS :MASKFLOAT :DRAGSOURCEMOVE :ADDFORMATTAG :VISIBLE :NC :INSERT
	       :ZORDER :X :Y :DRAGDROP :MASKREAL :LINEVALUE :EXPAND :VISIBLELINES :SIZE
      :PADDING :SPINMIN :WID :SELECTION :TIPMARKUP :FONTSIZE :NATURALSIZE
	       :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :TABSIZE :PROPAGATEFOCUS :BGCOLOR
      :XFONTID :PANGOFONTDESC :DROPTARGET :VALUEMASKED :ALIGNMENT :DRAGSOURCE
      :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :SCROLLTOPOS :FORMATTING
      :SCROLLTO :TIPRECT :TIPFGCOLOR :LINECOUNT :SPINWRAP :FONTFACE
      :VISIBLECOLUMNS :MASKINT :SPINVALUE :SPINALIGN :NAME :MASKCASEI
      :SELECTIONPOS :VALUE :FILTER :SPINMAX :MULTILINE :SELECTEDTEXT :ACTIVE
	       :TIPVISIBLE :CUEBANNER :EXPANDWEIGHT :MINSIZE :SPIN :BORDER :CHARSIZE
      :CARETPOS :SPINAUTO :MASK :DRAGTYPES :AUTOHIDE :FONTSTYLE :CLIPBOARD
	       :REMOVEFORMATTING :READONLY :APPEND :MASKNOEMPTY :FONT)
     :CALLBACKS
     (:FGCOLOR :COUNT :HANDLENAME :TIPBGCOLOR :WORDWRAP :PASSWORD :CARET
	       :MASKDECIMALSYMBOL :TIPICON :OVERWRITE :ADDFORMATTAG_HANDLE :SPININC
      :MAXSIZE :SCREENPOSITION :POSITION :APPENDNEWLINE :DROPFILESTARGET :TIP
      :CANFOCUS :MASKFLOAT :DRAGSOURCEMOVE :ADDFORMATTAG :VISIBLE :NC :INSERT
	       :ZORDER :X :Y :DRAGDROP :MASKREAL :LINEVALUE :EXPAND :VISIBLELINES :SIZE
      :PADDING :SPINMIN :WID :SELECTION :TIPMARKUP :FONTSIZE :NATURALSIZE
	       :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :TABSIZE :PROPAGATEFOCUS :BGCOLOR
      :XFONTID :PANGOFONTDESC :DROPTARGET :VALUEMASKED :ALIGNMENT :DRAGSOURCE
      :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :SCROLLTOPOS :FORMATTING
      :SCROLLTO :TIPRECT :TIPFGCOLOR :LINECOUNT :SPINWRAP :FONTFACE
      :VISIBLECOLUMNS :MASKINT :SPINVALUE :SPINALIGN :NAME :MASKCASEI
      :SELECTIONPOS :VALUE :FILTER :SPINMAX :MULTILINE :SELECTEDTEXT :ACTIVE
	       :TIPVISIBLE :CUEBANNER :EXPANDWEIGHT :MINSIZE :SPIN :BORDER :CHARSIZE
      :CARETPOS :SPINAUTO :MASK :DRAGTYPES :AUTOHIDE :FONTSTYLE :CLIPBOARD
	       :REMOVEFORMATTING :READONLY :APPEND :MASKNOEMPTY :FONT))
    (:CLASSNAME "radio" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :VALUE_HANDLE :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :VALUE :EXPAND
		:CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE
      :POSITION :CLIENTSIZE)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :VALUE_HANDLE :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :VALUE :EXPAND
		:CANFOCUS :RASTERSIZE :FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE
      :POSITION :CLIENTSIZE))
    (:CLASSNAME "gauge" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
	       :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
	       :LINEY :SHOW_TEXT :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :FLATCOLOR :EXPAND
      :DRAWFONT :SIZE :PADDING :POSX :POSY :WID :TIPMARKUP :YMIN :DRAWMAKEINACTIVE
	       :FONTSIZE :MIN :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR
      :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC
	       :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP
      :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR
      :YHIDDEN :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR
      :SHOWTEXT :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :VALUE
	       :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :MAX :FLAT :DASHED :BORDER
      :CHARSIZE :DRAGTYPES :FONTSTYLE :TEXT :TOUCH :XDISPLAY :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
	       :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
	       :LINEY :SHOW_TEXT :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :FLATCOLOR :EXPAND
      :DRAWFONT :SIZE :PADDING :POSX :POSY :WID :TIPMARKUP :YMIN :DRAWMAKEINACTIVE
	       :FONTSIZE :MIN :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR
      :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC
	       :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP
      :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR
      :YHIDDEN :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR
      :SHOWTEXT :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :VALUE
	       :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :MAX :FLAT :DASHED :BORDER
      :CHARSIZE :DRAGTYPES :FONTSTYLE :TEXT :TOUCH :XDISPLAY :FONT))
    (:CLASSNAME "colorbar" :ATTRIBUTES
     (:COUNT :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :SQUARED
      :SHOW_PREVIEW :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET
	     :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE
      :VISIBLE :NUM_CELLS :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y
	     :DRAGDROP :FLATCOLOR :EXPAND :DRAWFONT :SIZE :POSX :POSY :WID
	     :SECONDARY_CELL :TIPMARKUP :YMIN :ORIENTATION :DRAWMAKEINACTIVE :FONTSIZE
	     :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
      :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
      :DRAWABLE :SHOW_SECONDARY :DRAWTEXTELLIPSIS :SHADOWED :DRAGSOURCE
	     :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
	     :TIPFGCOLOR :YHIDDEN :DRAWSIZE :NUM_PARTS :FONTFACE :DRAWCOLOR
	     :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
	     :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :FLAT :BORDER
	     :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH :PREVIEW_SIZE :TRANSPARENCY
	     :PRIMARY_CELL :XDISPLAY :CELL :FONT)
     :CALLBACKS
     (:COUNT :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :SQUARED
      :SHOW_PREVIEW :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET
	     :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE
      :VISIBLE :NUM_CELLS :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y
	     :DRAGDROP :FLATCOLOR :EXPAND :DRAWFONT :SIZE :POSX :POSY :WID
	     :SECONDARY_CELL :TIPMARKUP :YMIN :ORIENTATION :DRAWMAKEINACTIVE :FONTSIZE
	     :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
      :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
      :DRAWABLE :SHOW_SECONDARY :DRAWTEXTELLIPSIS :SHADOWED :DRAGSOURCE
	     :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
	     :TIPFGCOLOR :YHIDDEN :DRAWSIZE :NUM_PARTS :FONTFACE :DRAWCOLOR
	     :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
	     :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :FLAT :BORDER
	     :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH :PREVIEW_SIZE :TRANSPARENCY
	     :PRIMARY_CELL :XDISPLAY :CELL :FONT))
    (:CLASSNAME "progressdlg" :ATTRIBUTES
     (:COUNT :PERCENT :HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL
	     :TIPICON :MENU :MAXSIZE :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY
      :POSITION :COMPOSITED :DROPFILESTARGET :BORDERSIZE :INC :TIP :CANFOCUS
	     :DRAGSOURCEMOVE :ICON :VISIBLE :CURSOR :MENUBOX :ZORDER :X :Y :HIDETITLEBAR
      :MAXBOX :DRAGDROP :DIALOGHINT :DIALOGFRAME :NACTIVE :SAVEUNDER
      :PROGRESSHEIGHT :CHILDOFFSET :EXPAND :SIZE :WID :TIPMARKUP :MDIMENU
	     :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
	     :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT :DESCRIPTION :PROPAGATEFOCUS
	     :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DRAGSOURCE :RESIZE :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE
      :MINPERCENT :TOPMOST :NAME :STATE :MINBOX :DEFAULTENTER :MODAL :PARENTDIALOG
      :BACKGROUND :HIDETASKBAR :BRINGFRONT :ACTIVE :TIPVISIBLE :EXPANDWEIGHT
      :MINSIZE :ACTIVEWINDOW :MINCLOCK :BORDER :SHRINK :CHARSIZE :CLIENTSIZE
	     :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE :MDICHILD :TOTALCOUNT
      :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL)
     :CALLBACKS
     (:COUNT :PERCENT :HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL
	     :TIPICON :MENU :MAXSIZE :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY
      :POSITION :COMPOSITED :DROPFILESTARGET :BORDERSIZE :INC :TIP :CANFOCUS
	     :DRAGSOURCEMOVE :ICON :VISIBLE :CURSOR :MENUBOX :ZORDER :X :Y :HIDETITLEBAR
      :MAXBOX :DRAGDROP :DIALOGHINT :DIALOGFRAME :NACTIVE :SAVEUNDER
      :PROGRESSHEIGHT :CHILDOFFSET :EXPAND :SIZE :WID :TIPMARKUP :MDIMENU
	     :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
	     :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT :DESCRIPTION :PROPAGATEFOCUS
	     :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DRAGSOURCE :RESIZE :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE
      :MINPERCENT :TOPMOST :NAME :STATE :MINBOX :DEFAULTENTER :MODAL :PARENTDIALOG
      :BACKGROUND :HIDETASKBAR :BRINGFRONT :ACTIVE :TIPVISIBLE :EXPANDWEIGHT
      :MINSIZE :ACTIVEWINDOW :MINCLOCK :BORDER :SHRINK :CHARSIZE :CLIENTSIZE
	     :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE :MDICHILD :TOTALCOUNT
      :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL))
    (:CLASSNAME "val" :ATTRIBUTES
     (:HANDLENAME :TIPBGCOLOR :TIPICON :STEP :MAXSIZE :SCREENPOSITION :POSITION
		  :TIP :TYPE :CANFOCUS :VISIBLE :ZORDER :X :Y :EXPAND :SIZE :WID :TIPMARKUP
      :ORIENTATION :TICKSPOS :FONTSIZE :MIN :NATURALSIZE :USERSIZE :TIPDELAY
		  :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :FLOATING :NORMALIZERGROUP
		  :PANGOLAYOUT :RASTERSIZE :PAGESTEP :TIPRECT :TIPFGCOLOR :FONTFACE :NAME
      :SHOWTICKS :VALUE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :MAX :INVERTED
      :CHARSIZE :FONTSTYLE :FONT)
     :CALLBACKS
     (:HANDLENAME :TIPBGCOLOR :TIPICON :STEP :MAXSIZE :SCREENPOSITION :POSITION
		  :TIP :TYPE :CANFOCUS :VISIBLE :ZORDER :X :Y :EXPAND :SIZE :WID :TIPMARKUP
      :ORIENTATION :TICKSPOS :FONTSIZE :MIN :NATURALSIZE :USERSIZE :TIPDELAY
		  :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :FLOATING :NORMALIZERGROUP
		  :PANGOLAYOUT :RASTERSIZE :PAGESTEP :TIPRECT :TIPFGCOLOR :FONTFACE :NAME
      :SHOWTICKS :VALUE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :MAX :INVERTED
      :CHARSIZE :FONTSTYLE :FONT))
    (:CLASSNAME "dial" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
	       :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :TYPE :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX
	       :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :FLATCOLOR :EXPAND
      :DRAWFONT :SIZE :POSX :POSY :WID :TIPMARKUP :YMIN :ORIENTATION
      :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
      :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
	       :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE
      :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
      :TIPFGCOLOR :YHIDDEN :UNIT :DRAWSIZE :FONTFACE :DRAWCOLOR
      :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
      :DRAWSTYLE :VALUE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :FLAT
      :BORDER :DENSITY :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH :XDISPLAY :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE
	       :DRAWTEXTWRAP :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT
      :TIP :DRAWTEXTLAYOUTCENTER :TYPE :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX
	       :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :FLATCOLOR :EXPAND
      :DRAWFONT :SIZE :POSX :POSY :WID :TIPMARKUP :YMIN :ORIENTATION
      :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
      :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
	       :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE
      :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
      :TIPFGCOLOR :YHIDDEN :UNIT :DRAWSIZE :FONTFACE :DRAWCOLOR
      :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
      :DRAWSTYLE :VALUE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE :FLAT
      :BORDER :DENSITY :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH :XDISPLAY :FONT))
    (:CLASSNAME "expander" :ATTRIBUTES
     (:HANDLENAME :FRAMETIME :IMAGEOPENHIGHLIGHT :IMAGEEXTRAPRESS1
      :IMAGEEXTRAPRESS2 :IMAGEEXTRAPRESS3 :BACKCOLOR :MAXSIZE :TITLEIMAGE
		  :POSITION :IMAGEEXTRA1 :IMAGEEXTRA2 :IMAGEEXTRA3 :CANFOCUS :VISIBLE :IMAGE
      :OPENCOLOR :HIGHCOLOR :EXPAND :SIZE :WID :FONTSIZE :NATURALSIZE :USERSIZE
      :TITLEIMAGEOPENHIGHLIGHT :TITLE :PROPAGATEFOCUS :XFONTID :PANGOFONTDESC
		  :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :IMAGEEXTRAHIGHLIGHT1
      :IMAGEEXTRAHIGHLIGHT2 :IMAGEEXTRAHIGHLIGHT3 :AUTOSHOW :BARSIZE :BARPOSITION
		  :FRAMECOLOR :FONTFACE :TITLEIMAGEOPEN :NAME :STATE :ACTIVE :IMAGEHIGHLIGHT
      :NUMFRAMES :EXPANDWEIGHT :MINSIZE :TITLEIMAGEHIGHLIGHT :EXTRABUTTONS
		  :ANIMATION :CHARSIZE :CLIENTSIZE :TITLEEXPAND :CLIENTOFFSET :FORECOLOR
		  :STATEREFRESH :FONTSTYLE :IMAGEOPEN :FRAMEWIDTH :FRAME :FONT)
     :CALLBACKS
     (:HANDLENAME :FRAMETIME :IMAGEOPENHIGHLIGHT :IMAGEEXTRAPRESS1
      :IMAGEEXTRAPRESS2 :IMAGEEXTRAPRESS3 :BACKCOLOR :MAXSIZE :TITLEIMAGE
		  :POSITION :IMAGEEXTRA1 :IMAGEEXTRA2 :IMAGEEXTRA3 :CANFOCUS :VISIBLE :IMAGE
      :OPENCOLOR :HIGHCOLOR :EXPAND :SIZE :WID :FONTSIZE :NATURALSIZE :USERSIZE
      :TITLEIMAGEOPENHIGHLIGHT :TITLE :PROPAGATEFOCUS :XFONTID :PANGOFONTDESC
		  :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :IMAGEEXTRAHIGHLIGHT1
      :IMAGEEXTRAHIGHLIGHT2 :IMAGEEXTRAHIGHLIGHT3 :AUTOSHOW :BARSIZE :BARPOSITION
		  :FRAMECOLOR :FONTFACE :TITLEIMAGEOPEN :NAME :STATE :ACTIVE :IMAGEHIGHLIGHT
      :NUMFRAMES :EXPANDWEIGHT :MINSIZE :TITLEIMAGEHIGHLIGHT :EXTRABUTTONS
		  :ANIMATION :CHARSIZE :CLIENTSIZE :TITLEEXPAND :CLIENTOFFSET :FORECOLOR
		  :STATEREFRESH :FONTSTYLE :IMAGEOPEN :FRAMEWIDTH :FRAME :FONT))
    (:CLASSNAME "cbox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION :CLIENTSIZE)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION :CLIENTSIZE))
    (:CLASSNAME "separator" :ATTRIBUTES (:NAME :WID) :CALLBACKS (:NAME :WID))
    (:CLASSNAME "menu" :ATTRIBUTES (:BGCOLOR :FONT :NAME :WID :RADIO) :CALLBACKS
     (:BGCOLOR :FONT :NAME :WID :RADIO))
    (:CLASSNAME "flattoggle" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :CHECKFGCOLOR :HASFOCUS
      :FRONTIMAGEHIGHLIGHT :XMIN :TIPICON :CHECKIMAGENOTDEFHIGHLIGHT :CHECKRIGHT
	       :MAXSIZE :DRAWTEXTWRAP :CHECKIMAGENOTDEFINACTIVE :SCREENPOSITION
	       :CHECKIMAGEHIGHLIGHT :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP
      :DRAWTEXTLAYOUTCENTER :CHECKIMAGEONINACTIVE :CANFOCUS :DRAGSOURCEMOVE
      :PSCOLOR :VISIBLE :IMAGE :CHECKPSCOLOR :LINEX :CURSOR :LINEY :ZORDER
      :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :CHECKIMAGEONPRESS :DRAWFONT :SIZE
      :PADDING :POSX :POSY :WID :BORDERHLCOLOR :TIPMARKUP :YMIN :CHECKIMAGE
      :TEXTCLIP :TEXTELLIPSIS :CHECKIMAGENOTDEF :DRAWMAKEINACTIVE :FONTSIZE
	       :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :BACKIMAGEINACTIVE :SCROLLBAR
	       :XHIDDEN :TITLE :XAUTOHIDE :RADIO :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
	       :PANGOFONTDESC :CHECKIMAGEPRESS :DROPTARGET :HIGHLIGHTED :CHECKBGCOLOR :DX
	       :DY :DRAWABLE :ALIGNMENT :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP
	       :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :SPACING :BORDERPSCOLOR :RASTERSIZE
	       :CHECKSPACING :BORDERCOLOR :TIPRECT :TIPFGCOLOR :YHIDDEN
      :CHECKIMAGEONHIGHLIGHT :FRONTIMAGEINACTIVE :BACKIMAGEHIGHLIGHT
	       :FRONTIMAGEPRESS :DRAWSIZE :HLCOLOR :FRONTIMAGE :CHECKHLCOLOR
      :CHECKIMAGENOTDEFPRESS :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION
      :DRAWBGCOLOR :IMAGEPRESS :NAME :BACKINGSTORE :CHECKIMAGEINACTIVE :DRAWDRIVER
      :YAUTOHIDE :DRAWSTYLE :VALUE :BACKIMAGEZOOM :TEXTORIENTATION :FITTOBACKIMAGE
      :ACTIVE :TIPVISIBLE :IMAGEHIGHLIGHT :YMAX :BACKIMAGE :IMAGEINACTIVE
      :EXPANDWEIGHT :MINSIZE :SHOWBORDER :CHECKSIZE :BORDER :CHARSIZE :IGNORERADIO
	       :IMAGEPOSITION :DRAGTYPES :BORDERWIDTH :FONTSTYLE :TEXTALIGNMENT :TOUCH
	       :CHECKIMAGEON :TEXTWRAP :XDISPLAY :BACKIMAGEPRESS :FONT :PRESSED)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :CHECKFGCOLOR :HASFOCUS
      :FRONTIMAGEHIGHLIGHT :XMIN :TIPICON :CHECKIMAGENOTDEFHIGHLIGHT :CHECKRIGHT
	       :MAXSIZE :DRAWTEXTWRAP :CHECKIMAGENOTDEFINACTIVE :SCREENPOSITION
	       :CHECKIMAGEHIGHLIGHT :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP
      :DRAWTEXTLAYOUTCENTER :CHECKIMAGEONINACTIVE :CANFOCUS :DRAGSOURCEMOVE
      :PSCOLOR :VISIBLE :IMAGE :CHECKPSCOLOR :LINEX :CURSOR :LINEY :ZORDER
      :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :CHECKIMAGEONPRESS :DRAWFONT :SIZE
      :PADDING :POSX :POSY :WID :BORDERHLCOLOR :TIPMARKUP :YMIN :CHECKIMAGE
      :TEXTCLIP :TEXTELLIPSIS :CHECKIMAGENOTDEF :DRAWMAKEINACTIVE :FONTSIZE
	       :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :BACKIMAGEINACTIVE :SCROLLBAR
	       :XHIDDEN :TITLE :XAUTOHIDE :RADIO :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID
	       :PANGOFONTDESC :CHECKIMAGEPRESS :DROPTARGET :HIGHLIGHTED :CHECKBGCOLOR :DX
	       :DY :DRAWABLE :ALIGNMENT :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP
	       :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :SPACING :BORDERPSCOLOR :RASTERSIZE
	       :CHECKSPACING :BORDERCOLOR :TIPRECT :TIPFGCOLOR :YHIDDEN
      :CHECKIMAGEONHIGHLIGHT :FRONTIMAGEINACTIVE :BACKIMAGEHIGHLIGHT
	       :FRONTIMAGEPRESS :DRAWSIZE :HLCOLOR :FRONTIMAGE :CHECKHLCOLOR
      :CHECKIMAGENOTDEFPRESS :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION
      :DRAWBGCOLOR :IMAGEPRESS :NAME :BACKINGSTORE :CHECKIMAGEINACTIVE :DRAWDRIVER
      :YAUTOHIDE :DRAWSTYLE :VALUE :BACKIMAGEZOOM :TEXTORIENTATION :FITTOBACKIMAGE
      :ACTIVE :TIPVISIBLE :IMAGEHIGHLIGHT :YMAX :BACKIMAGE :IMAGEINACTIVE
      :EXPANDWEIGHT :MINSIZE :SHOWBORDER :CHECKSIZE :BORDER :CHARSIZE :IGNORERADIO
	       :IMAGEPOSITION :DRAGTYPES :BORDERWIDTH :FONTSTYLE :TEXTALIGNMENT :TOUCH
	       :CHECKIMAGEON :TEXTWRAP :XDISPLAY :BACKIMAGEPRESS :FONT :PRESSED))
    (:CLASSNAME "calendar" :ATTRIBUTES
     (:HANDLENAME :TIPBGCOLOR :TODAY :TIPICON :MAXSIZE :SCREENPOSITION :POSITION
		  :TIP :CANFOCUS :VISIBLE :ZORDER :X :Y :EXPAND :SIZE :WID :TIPMARKUP
		  :FONTSIZE :NATURALSIZE :USERSIZE :TIPDELAY :PROPAGATEFOCUS :XFONTID
		  :PANGOFONTDESC :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
		  :TIPFGCOLOR :FONTFACE :NAME :VALUE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT
      :MINSIZE :CHARSIZE :FONTSTYLE :WEEKNUMBERS :FONT)
     :CALLBACKS
     (:HANDLENAME :TIPBGCOLOR :TODAY :TIPICON :MAXSIZE :SCREENPOSITION :POSITION
		  :TIP :CANFOCUS :VISIBLE :ZORDER :X :Y :EXPAND :SIZE :WID :TIPMARKUP
		  :FONTSIZE :NATURALSIZE :USERSIZE :TIPDELAY :PROPAGATEFOCUS :XFONTID
		  :PANGOFONTDESC :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT
		  :TIPFGCOLOR :FONTFACE :NAME :VALUE :ACTIVE :TIPVISIBLE :EXPANDWEIGHT
      :MINSIZE :CHARSIZE :FONTSTYLE :WEEKNUMBERS :FONT))
    (:CLASSNAME "item" :ATTRIBUTES
     (:ACTIVE :TITLE :IMPRESS :HIDEMARK :IMAGE :BGCOLOR :TITLEIMAGE :KEY :FONT
	      :NAME :VALUE :WID :AUTOTOGGLE)
     :CALLBACKS
     (:ACTIVE :TITLE :IMPRESS :HIDEMARK :IMAGE :BGCOLOR :TITLEIMAGE :KEY :FONT
	      :NAME :VALUE :WID :AUTOTOGGLE))
    (:CLASSNAME "parambox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :MODIFIABLE :ACTIVE
		:NATURALSIZE :VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :STATUS
		:CHARSIZE :HANDLENAME :SIZE :NORMALIZERGROUP :USERDATA :BUTTON1
		:PANGOFONTDESC :BUTTON2 :BUTTON3 :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:FLOATING :WID :PANGOLAYOUT :PARAMCOUNT :XFONTID :MINSIZE :LABELALIGN
      :POSITION :CLIENTSIZE)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :MODIFIABLE :ACTIVE
		:NATURALSIZE :VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :STATUS
		:CHARSIZE :HANDLENAME :SIZE :NORMALIZERGROUP :USERDATA :BUTTON1
		:PANGOFONTDESC :BUTTON2 :BUTTON3 :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:FLOATING :WID :PANGOLAYOUT :PARAMCOUNT :XFONTID :MINSIZE :LABELALIGN
      :POSITION :CLIENTSIZE))
    (:CLASSNAME "flatbutton" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :HASFOCUS :FRONTIMAGEHIGHLIGHT
      :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP :SCREENPOSITION :POSITION
      :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS
	       :DRAGSOURCEMOVE :PSCOLOR :VISIBLE :IMAGE :LINEX :CURSOR :LINEY :ZORDER
	       :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :PADDING :POSX :POSY
	       :WID :BORDERHLCOLOR :TIPMARKUP :YMIN :TOGGLE :TEXTCLIP :TEXTELLIPSIS
      :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
      :BACKIMAGEINACTIVE :SCROLLBAR :XHIDDEN :TITLE :XAUTOHIDE :RADIO
      :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET
      :HIGHLIGHTED :DX :DY :DRAWABLE :ALIGNMENT :DRAWTEXTELLIPSIS :DRAGSOURCE
	       :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :SPACING
      :BORDERPSCOLOR :RASTERSIZE :BORDERCOLOR :TIPRECT :TIPFGCOLOR :YHIDDEN
      :FRONTIMAGEINACTIVE :BACKIMAGEHIGHLIGHT :FRONTIMAGEPRESS :DRAWSIZE :HLCOLOR
	       :FRONTIMAGE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR
      :IMAGEPRESS :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :VALUE
	       :BACKIMAGEZOOM :TEXTORIENTATION :FITTOBACKIMAGE :ACTIVE :TIPVISIBLE
      :IMAGEHIGHLIGHT :YMAX :BACKIMAGE :IMAGEINACTIVE :EXPANDWEIGHT :MINSIZE
      :SHOWBORDER :BORDER :CHARSIZE :IGNORERADIO :IMAGEPOSITION :DRAGTYPES
      :BORDERWIDTH :FONTSTYLE :TEXTALIGNMENT :TOUCH :TEXTWRAP :XDISPLAY
      :BACKIMAGEPRESS :FONT :PRESSED)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :XWINDOW :TIPBGCOLOR :HASFOCUS :FRONTIMAGEHIGHLIGHT
      :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP :SCREENPOSITION :POSITION
      :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS
	       :DRAGSOURCEMOVE :PSCOLOR :VISIBLE :IMAGE :LINEX :CURSOR :LINEY :ZORDER
	       :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :PADDING :POSX :POSY
	       :WID :BORDERHLCOLOR :TIPMARKUP :YMIN :TOGGLE :TEXTCLIP :TEXTELLIPSIS
      :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
      :BACKIMAGEINACTIVE :SCROLLBAR :XHIDDEN :TITLE :XAUTOHIDE :RADIO
      :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET
      :HIGHLIGHTED :DX :DY :DRAWABLE :ALIGNMENT :DRAWTEXTELLIPSIS :DRAGSOURCE
	       :DRAWTEXTCLIP :FLOATING :NORMALIZERGROUP :PANGOLAYOUT :SPACING
      :BORDERPSCOLOR :RASTERSIZE :BORDERCOLOR :TIPRECT :TIPFGCOLOR :YHIDDEN
      :FRONTIMAGEINACTIVE :BACKIMAGEHIGHLIGHT :FRONTIMAGEPRESS :DRAWSIZE :HLCOLOR
	       :FRONTIMAGE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR
      :IMAGEPRESS :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :VALUE
	       :BACKIMAGEZOOM :TEXTORIENTATION :FITTOBACKIMAGE :ACTIVE :TIPVISIBLE
      :IMAGEHIGHLIGHT :YMAX :BACKIMAGE :IMAGEINACTIVE :EXPANDWEIGHT :MINSIZE
      :SHOWBORDER :BORDER :CHARSIZE :IGNORERADIO :IMAGEPOSITION :DRAGTYPES
      :BORDERWIDTH :FONTSTYLE :TEXTALIGNMENT :TOUCH :TEXTWRAP :XDISPLAY
      :BACKIMAGEPRESS :FONT :PRESSED))
    (:CLASSNAME "canvas" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP
		  :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP
      :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
      :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :POSX
      :POSY :WID :TIPMARKUP :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE
		  :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
		  :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
		  :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN
      :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME
      :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX
		  :EXPANDWEIGHT :MINSIZE :BORDER :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH
      :XDISPLAY :FONT)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP
		  :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :TIP
      :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :LINEX :CURSOR
      :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :POSX
      :POSY :WID :TIPMARKUP :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE
		  :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
		  :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
		  :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN
      :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME
      :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX
		  :EXPANDWEIGHT :MINSIZE :BORDER :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH
      :XDISPLAY :FONT))
    (:CLASSNAME "dialog" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP :DIALOGHINT
      :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND :SIZE :WID :TIPMARKUP
      :MDIMENU :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
		  :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT :PROPAGATEFOCUS :BGCOLOR :XFONTID
      :PANGOFONTDESC :DROPTARGET :DRAGSOURCE :RESIZE :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :TOPMOST :NAME
		  :MINBOX :DEFAULTENTER :MODAL :PARENTDIALOG :BACKGROUND :HIDETASKBAR
		  :BRINGFRONT :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW :BORDER
      :SHRINK :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME
		  :FONTSTYLE :MDICHILD :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP :DIALOGHINT
      :DIALOGFRAME :NACTIVE :SAVEUNDER :CHILDOFFSET :EXPAND :SIZE :WID :TIPMARKUP
      :MDIMENU :STARTFOCUS :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY
		  :CUSTOMFRAME :TITLE :DEFAULTESC :PLACEMENT :PROPAGATEFOCUS :BGCOLOR :XFONTID
      :PANGOFONTDESC :DROPTARGET :DRAGSOURCE :RESIZE :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :TOPMOST :NAME
		  :MINBOX :DEFAULTENTER :MODAL :PARENTDIALOG :BACKGROUND :HIDETASKBAR
		  :BRINGFRONT :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW :BORDER
      :SHRINK :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME
		  :FONTSTYLE :MDICHILD :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL))
    (:CLASSNAME "user" :ATTRIBUTES (:CLEARATTRIBUTES) :CALLBACKS
     (:CLEARATTRIBUTES))
    (:CLASSNAME "colorbrowser" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP
		  :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :HSI :TIP
		  :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :RGB :VISIBLE :LINEX :CURSOR
      :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :POSX
      :POSY :WID :TIPMARKUP :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE
		  :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
		  :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
		  :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN
      :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME
      :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX
		  :EXPANDWEIGHT :MINSIZE :BORDER :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH
      :XDISPLAY :FONT)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :XMIN :TIPICON :MAXSIZE :DRAWTEXTWRAP
		  :SCREENPOSITION :POSITION :DROPFILESTARGET :DRAWTEXTALIGNMENT :HSI :TIP
		  :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :RGB :VISIBLE :LINEX :CURSOR
      :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :DRAGDROP :EXPAND :DRAWFONT :SIZE :POSX
      :POSY :WID :TIPMARKUP :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE
		  :DROPTYPES :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE
		  :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY
		  :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
      :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :YHIDDEN
      :DRAWSIZE :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME
      :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX
		  :EXPANDWEIGHT :MINSIZE :BORDER :CHARSIZE :DRAGTYPES :FONTSTYLE :TOUCH
      :XDISPLAY :FONT))
    (:CLASSNAME "toggle" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :TIPICON :RIGHTBUTTON :MAXSIZE
      :SCREENPOSITION :POSITION :IMPRESS :IMINACTIVE :TIP :CANFOCUS :VISIBLE
	       :IMAGE :ZORDER :X :Y :EXPAND :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE
	       :NATURALSIZE :USERSIZE :TIPDELAY :TITLE :RADIO :PROPAGATEFOCUS :BGCOLOR
      :XFONTID :PANGOFONTDESC :ALIGNMENT :MARKUP :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :3STATE :NAME :VALUE
      :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :FLAT :CHARSIZE :IGNORERADIO
	       :FONTSTYLE :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :TIPICON :RIGHTBUTTON :MAXSIZE
      :SCREENPOSITION :POSITION :IMPRESS :IMINACTIVE :TIP :CANFOCUS :VISIBLE
	       :IMAGE :ZORDER :X :Y :EXPAND :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE
	       :NATURALSIZE :USERSIZE :TIPDELAY :TITLE :RADIO :PROPAGATEFOCUS :BGCOLOR
      :XFONTID :PANGOFONTDESC :ALIGNMENT :MARKUP :FLOATING :NORMALIZERGROUP
      :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :3STATE :NAME :VALUE
      :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :FLAT :CHARSIZE :IGNORERADIO
	       :FONTSTYLE :FONT))
    (:CLASSNAME "spinbox" :ATTRIBUTES
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION :CLIENTSIZE)
     :CALLBACKS
     (:USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE :NATURALSIZE
		:VISIBLE :CLIENTOFFSET :FONTFACE :PROPAGATEFOCUS :CHARSIZE :HANDLENAME :SIZE
      :NORMALIZERGROUP :PANGOFONTDESC :FONT :NAME :EXPAND :CANFOCUS :RASTERSIZE
		:FLOATING :WID :PANGOLAYOUT :XFONTID :MINSIZE :POSITION :CLIENTSIZE))
    (:CLASSNAME "link" :ATTRIBUTES
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :WORDWRAP :TIPICON :MAXSIZE :SCREENPOSITION
	       :POSITION :IMINACTIVE :DROPFILESTARGET :TIP :CANFOCUS :DRAGSOURCEMOVE
	       :VISIBLE :SEPARATOR :IMAGE :CURSOR :ZORDER :X :Y :URL :DRAGDROP :EXPAND
	       :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE
	       :TIPDELAY :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC
	       :DROPTARGET :ALIGNMENT :DRAGSOURCE :MARKUP :FLOATING :NORMALIZERGROUP
	       :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :NAME :ELLIPSIS
      :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :CHARSIZE :DRAGTYPES :FONTSTYLE
	       :FONT)
     :CALLBACKS
     (:FGCOLOR :HANDLENAME :TIPBGCOLOR :WORDWRAP :TIPICON :MAXSIZE :SCREENPOSITION
	       :POSITION :IMINACTIVE :DROPFILESTARGET :TIP :CANFOCUS :DRAGSOURCEMOVE
	       :VISIBLE :SEPARATOR :IMAGE :CURSOR :ZORDER :X :Y :URL :DRAGDROP :EXPAND
	       :SIZE :PADDING :WID :TIPMARKUP :FONTSIZE :NATURALSIZE :DROPTYPES :USERSIZE
	       :TIPDELAY :TITLE :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC
	       :DROPTARGET :ALIGNMENT :DRAGSOURCE :MARKUP :FLOATING :NORMALIZERGROUP
	       :PANGOLAYOUT :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :NAME :ELLIPSIS
      :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :CHARSIZE :DRAGTYPES :FONTSTYLE
	       :FONT))
    (:CLASSNAME "imagergb" :ATTRIBUTES
     (:RESIZE :SCALED :BPP :RESHAPE :CHANNELS :HOTSPOT :HEIGHT :CLEARCACHE
      :BGCOLOR :ORIGINALSCALE :WIDTH :RASTERSIZE :WID)
     :CALLBACKS
     (:RESIZE :SCALED :BPP :RESHAPE :CHANNELS :HOTSPOT :HEIGHT :CLEARCACHE
      :BGCOLOR :ORIGINALSCALE :WIDTH :RASTERSIZE :WID))
    (:CLASSNAME "progressbar" :ATTRIBUTES
     (:TIPBGCOLOR :USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE
		  :FGCOLOR :MARQUEE :NATURALSIZE :SCREENPOSITION :VISIBLE :TIPMARKUP :FONTFACE
      :ZORDER :TIP :PROPAGATEFOCUS :MAX :CHARSIZE :HANDLENAME :SIZE :BGCOLOR
      :NORMALIZERGROUP :PANGOFONTDESC :TIPFGCOLOR :FONT :NAME :VALUE :TIPVISIBLE
		  :TIPDELAY :EXPAND :CANFOCUS :DASHED :RASTERSIZE :FLOATING :MIN :ORIENTATION
		  :WID :X :PANGOLAYOUT :Y :XFONTID :MINSIZE :TIPICON :POSITION :TIPRECT)
     :CALLBACKS
     (:TIPBGCOLOR :USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE :ACTIVE
		  :FGCOLOR :MARQUEE :NATURALSIZE :SCREENPOSITION :VISIBLE :TIPMARKUP :FONTFACE
      :ZORDER :TIP :PROPAGATEFOCUS :MAX :CHARSIZE :HANDLENAME :SIZE :BGCOLOR
      :NORMALIZERGROUP :PANGOFONTDESC :TIPFGCOLOR :FONT :NAME :VALUE :TIPVISIBLE
		  :TIPDELAY :EXPAND :CANFOCUS :DASHED :RASTERSIZE :FLOATING :MIN :ORIENTATION
		  :WID :X :PANGOLAYOUT :Y :XFONTID :MINSIZE :TIPICON :POSITION :TIPRECT))
    (:CLASSNAME "flatscrollbox" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :IMAGEBOTTOMPRESS :XMIN
      :IMAGERIGHT :IMAGELEFTHIGHLIGHT :TIPICON :BACKCOLOR :MAXSIZE :DRAWTEXTWRAP
      :SCREENPOSITION :POSITION :DROPFILESTARGET :FLOATINGDELAY :DRAWTEXTALIGNMENT
		  :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :IMAGETOP
		  :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :IMAGETOPPRESS :DRAGDROP
      :HIGHCOLOR :PRESSCOLOR :SCROLLTOCHILD :SHOWARROWS :CHILDOFFSET
		  :SCROLLTOCHILD_HANDLE :EXPAND :IMAGELEFTINACTIVE :DRAWFONT :SIZE :POSX :POSY
      :WID :TIPMARKUP :YMIN :SHOWFLOATING :DRAWMAKEINACTIVE :FONTSIZE
      :IMAGELEFTPRESS :NATURALSIZE :IMAGERIGHTHIGHLIGHT :DROPTYPES :USERSIZE
		  :TIPDELAY :IMAGERIGHTPRESS :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS
		  :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE
		  :DRAWTEXTELLIPSIS :DRAGSOURCE :IMAGEBOTTOM :DRAWTEXTCLIP :LAYOUTDRAG
      :FLOATING :IMAGETOPHIGHLIGHT :NORMALIZERGROUP :PANGOLAYOUT
      :IMAGEBOTTOMINACTIVE :RASTERSIZE :IMAGEBOTTOMHIGHLIGHT :FLATSCROLLBAR
      :SCROLLTO :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE :FONTFACE :DRAWCOLOR
		  :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
		  :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE
		  :IMAGERIGHTINACTIVE :ARROWIMAGES :IMAGELEFT :BORDER :CHARSIZE :CLIENTSIZE
		  :SCROLLBARSIZE :CLIENTOFFSET :FORECOLOR :DRAGTYPES :IMAGETOPINACTIVE
      :FONTSTYLE :TOUCH :XDISPLAY :FONT)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :CANVASBOX :TIPBGCOLOR :IMAGEBOTTOMPRESS :XMIN
      :IMAGERIGHT :IMAGELEFTHIGHLIGHT :TIPICON :BACKCOLOR :MAXSIZE :DRAWTEXTWRAP
      :SCREENPOSITION :POSITION :DROPFILESTARGET :FLOATINGDELAY :DRAWTEXTALIGNMENT
		  :TIP :DRAWTEXTLAYOUTCENTER :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :IMAGETOP
		  :LINEX :CURSOR :LINEY :ZORDER :DRAWLINEWIDTH :X :Y :IMAGETOPPRESS :DRAGDROP
      :HIGHCOLOR :PRESSCOLOR :SCROLLTOCHILD :SHOWARROWS :CHILDOFFSET
		  :SCROLLTOCHILD_HANDLE :EXPAND :IMAGELEFTINACTIVE :DRAWFONT :SIZE :POSX :POSY
      :WID :TIPMARKUP :YMIN :SHOWFLOATING :DRAWMAKEINACTIVE :FONTSIZE
      :IMAGELEFTPRESS :NATURALSIZE :IMAGERIGHTHIGHLIGHT :DROPTYPES :USERSIZE
		  :TIPDELAY :IMAGERIGHTPRESS :SCROLLBAR :XHIDDEN :XAUTOHIDE :PROPAGATEFOCUS
		  :XMAX :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET :DX :DY :DRAWABLE
		  :DRAWTEXTELLIPSIS :DRAGSOURCE :IMAGEBOTTOM :DRAWTEXTCLIP :LAYOUTDRAG
      :FLOATING :IMAGETOPHIGHLIGHT :NORMALIZERGROUP :PANGOLAYOUT
      :IMAGEBOTTOMINACTIVE :RASTERSIZE :IMAGEBOTTOMHIGHLIGHT :FLATSCROLLBAR
      :SCROLLTO :TIPRECT :TIPFGCOLOR :YHIDDEN :DRAWSIZE :FONTFACE :DRAWCOLOR
		  :DRAWTEXTORIENTATION :DRAWBGCOLOR :NAME :BACKINGSTORE :DRAWDRIVER :YAUTOHIDE
		  :DRAWSTYLE :ACTIVE :TIPVISIBLE :YMAX :EXPANDWEIGHT :MINSIZE
		  :IMAGERIGHTINACTIVE :ARROWIMAGES :IMAGELEFT :BORDER :CHARSIZE :CLIENTSIZE
		  :SCROLLBARSIZE :CLIENTOFFSET :FORECOLOR :DRAGTYPES :IMAGETOPINACTIVE
      :FONTSTYLE :TOUCH :XDISPLAY :FONT))
    (:CLASSNAME "messagedlg" :ATTRIBUTES
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :DIALOGTYPE :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP
      :DIALOGHINT :DIALOGFRAME :NACTIVE :SAVEUNDER :BUTTONS :CHILDOFFSET :EXPAND
		  :SIZE :WID :TIPMARKUP :BUTTONRESPONSE :MDIMENU :STARTFOCUS :FONTSIZE
      :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :CUSTOMFRAME :TITLE :DEFAULTESC
		  :PLACEMENT :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET
		  :DRAGSOURCE :BUTTONDEFAULT :RESIZE :FLOATING :NORMALIZERGROUP :PANGOLAYOUT
		  :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :TOPMOST :NAME :MINBOX
      :DEFAULTENTER :MODAL :PARENTDIALOG :BACKGROUND :HIDETASKBAR :BRINGFRONT
      :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW :BORDER :SHRINK
		  :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE
      :MDICHILD :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL)
     :CALLBACKS
     (:HANDLENAME :XWINDOW :TIPBGCOLOR :MDICLIENT :CONTROL :TIPICON :MENU :MAXSIZE
      :OPACITYIMAGE :HELPBUTTON :SCREENPOSITION :OPACITY :POSITION :COMPOSITED
      :DROPFILESTARGET :BORDERSIZE :TIP :CANFOCUS :DRAGSOURCEMOVE :ICON :VISIBLE
		  :CURSOR :MENUBOX :DIALOGTYPE :ZORDER :X :Y :HIDETITLEBAR :MAXBOX :DRAGDROP
      :DIALOGHINT :DIALOGFRAME :NACTIVE :SAVEUNDER :BUTTONS :CHILDOFFSET :EXPAND
		  :SIZE :WID :TIPMARKUP :BUTTONRESPONSE :MDIMENU :STARTFOCUS :FONTSIZE
      :NATURALSIZE :DROPTYPES :USERSIZE :TIPDELAY :CUSTOMFRAME :TITLE :DEFAULTESC
		  :PLACEMENT :PROPAGATEFOCUS :BGCOLOR :XFONTID :PANGOFONTDESC :DROPTARGET
		  :DRAGSOURCE :BUTTONDEFAULT :RESIZE :FLOATING :NORMALIZERGROUP :PANGOLAYOUT
		  :RASTERSIZE :TIPRECT :TIPFGCOLOR :FONTFACE :TOPMOST :NAME :MINBOX
      :DEFAULTENTER :MODAL :PARENTDIALOG :BACKGROUND :HIDETASKBAR :BRINGFRONT
      :ACTIVE :TIPVISIBLE :EXPANDWEIGHT :MINSIZE :ACTIVEWINDOW :BORDER :SHRINK
		  :CHARSIZE :CLIENTSIZE :CLIENTOFFSET :DRAGTYPES :TOOLBOX :MDIFRAME :FONTSTYLE
      :MDICHILD :FULLSCREEN :NATIVEPARENT :FONT :SIMULATEMODAL))
    (:CLASSNAME "frame" :ATTRIBUTES
     (:TIPBGCOLOR :USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE
      :CHILDOFFSET :SUNKEN :ACTIVE :TITLE :FGCOLOR :NATURALSIZE :SCREENPOSITION
		  :VISIBLE :TIPMARKUP :CLIENTOFFSET :FONTFACE :ZORDER :TIP :PROPAGATEFOCUS
      :CHARSIZE :HANDLENAME :SIZE :BGCOLOR :NORMALIZERGROUP :PANGOFONTDESC
      :TIPFGCOLOR :FONT :NAME :TIPVISIBLE :TIPDELAY :EXPAND :CANFOCUS :RASTERSIZE
      :FLOATING :WID :X :PANGOLAYOUT :Y :XFONTID :MINSIZE :TIPICON :POSITION
		  :CLIENTSIZE :TIPRECT)
     :CALLBACKS
     (:TIPBGCOLOR :USERSIZE :FONTSTYLE :FONTSIZE :EXPANDWEIGHT :MAXSIZE
      :CHILDOFFSET :SUNKEN :ACTIVE :TITLE :FGCOLOR :NATURALSIZE :SCREENPOSITION
		  :VISIBLE :TIPMARKUP :CLIENTOFFSET :FONTFACE :ZORDER :TIP :PROPAGATEFOCUS
      :CHARSIZE :HANDLENAME :SIZE :BGCOLOR :NORMALIZERGROUP :PANGOFONTDESC
      :TIPFGCOLOR :FONT :NAME :TIPVISIBLE :TIPDELAY :EXPAND :CANFOCUS :RASTERSIZE
      :FLOATING :WID :X :PANGOLAYOUT :Y :XFONTID :MINSIZE :TIPICON :POSITION
		  :CLIENTSIZE :TIPRECT))
    (:CLASSNAME "flattabs" :ATTRIBUTES
     (:COUNT :HANDLENAME :XWINDOW :TIPBGCOLOR :HASFOCUS :TABFONTSIZE :XMIN
	     :TIPICON :EXPANDBUTTONPOS :TABSFORECOLOR :MAXSIZE :EXTRAIMAGE :DRAWTEXTWRAP
	     :SCREENPOSITION :TABFONT :POSITION :TABHIGHCOLOR :DROPFILESTARGET
      :DRAWTEXTALIGNMENT :EXPANDBUTTON :TIP :DRAWTEXTLAYOUTCENTER :SHOWCLOSE
	     :FIXEDWIDTH :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :TABSTEXTWRAP :LINEX :CURSOR
      :LINEY :CLOSEPRESSCOLOR :ZORDER :TABTIP :DRAWLINEWIDTH :X :Y
	     :TABSTEXTELLIPSIS :SHOWLINES :DRAGDROP :HIGHCOLOR :TABSFONT :TABSFONTSIZE
	     :EXTRAFORECOLOR :EXPANDBUTTONSTATE :CHILDOFFSET :EXPAND :DRAWFONT :SIZE
	     :TABCHANGEONCHECK :POSX :POSY :WID :EXTRATITLE :TABBACKCOLOR :TIPMARKUP
      :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :EXTRAIMAGEPRESS :DROPTYPES
      :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE :TABVISIBLE
      :TABSIMAGESPACING :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :VALUE_HANDLE
      :CLOSEIMAGEHIGHLIGHT :TABSFONTSTYLE :PANGOFONTDESC :DROPTARGET :DX :DY
      :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
	     :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :CLOSEIMAGEINACTIVE :EXTRAACTIVE
      :TIPRECT :TIPFGCOLOR :YHIDDEN :TABSPADDING :TABSIMAGEPOSITION :DRAWSIZE
      :TABSTEXTCLIP :CLOSEIMAGEPRESS :EXTRATIP :TABSTEXTALIGNMENT :EXTRAPRESSCOLOR
	     :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :EXTRAHIGHCOLOR
      :TABORIENTATION :TABSLINECOLOR :NAME :TABSBACKCOLOR :VALUEPOS :BACKINGSTORE
      :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :TABSALIGNMENT :VALUE :TABIMAGE :ACTIVE
	     :TIPVISIBLE :TABFORECOLOR :EXTRAFONT :YMAX :TABSTEXTORIENTATION
      :EXPANDWEIGHT :MINSIZE :CLOSEHIGHCOLOR :TABFONTSTYLE :CLOSEIMAGE
	     :EXTRAIMAGEINACTIVE :EXTRABUTTONS :BORDER :TABSHIGHCOLOR :CHARSIZE
      :CLIENTSIZE :CLIENTOFFSET :FORECOLOR :DRAGTYPES :EXTRAALIGNMENT :FONTSTYLE
      :TOUCH :TABTITLE :EXTRAIMAGEHIGHLIGHT :XDISPLAY :TABACTIVE :FONT)
     :CALLBACKS
     (:COUNT :HANDLENAME :XWINDOW :TIPBGCOLOR :HASFOCUS :TABFONTSIZE :XMIN
	     :TIPICON :EXPANDBUTTONPOS :TABSFORECOLOR :MAXSIZE :EXTRAIMAGE :DRAWTEXTWRAP
	     :SCREENPOSITION :TABFONT :POSITION :TABHIGHCOLOR :DROPFILESTARGET
      :DRAWTEXTALIGNMENT :EXPANDBUTTON :TIP :DRAWTEXTLAYOUTCENTER :SHOWCLOSE
	     :FIXEDWIDTH :CANFOCUS :DRAGSOURCEMOVE :VISIBLE :TABSTEXTWRAP :LINEX :CURSOR
      :LINEY :CLOSEPRESSCOLOR :ZORDER :TABTIP :DRAWLINEWIDTH :X :Y
	     :TABSTEXTELLIPSIS :SHOWLINES :DRAGDROP :HIGHCOLOR :TABSFONT :TABSFONTSIZE
	     :EXTRAFORECOLOR :EXPANDBUTTONSTATE :CHILDOFFSET :EXPAND :DRAWFONT :SIZE
	     :TABCHANGEONCHECK :POSX :POSY :WID :EXTRATITLE :TABBACKCOLOR :TIPMARKUP
      :YMIN :DRAWMAKEINACTIVE :FONTSIZE :NATURALSIZE :EXTRAIMAGEPRESS :DROPTYPES
      :USERSIZE :TIPDELAY :SCROLLBAR :XHIDDEN :XAUTOHIDE :TABVISIBLE
      :TABSIMAGESPACING :PROPAGATEFOCUS :XMAX :BGCOLOR :XFONTID :VALUE_HANDLE
      :CLOSEIMAGEHIGHLIGHT :TABSFONTSTYLE :PANGOFONTDESC :DROPTARGET :DX :DY
      :DRAWABLE :DRAWTEXTELLIPSIS :DRAGSOURCE :DRAWTEXTCLIP :FLOATING
	     :NORMALIZERGROUP :PANGOLAYOUT :RASTERSIZE :CLOSEIMAGEINACTIVE :EXTRAACTIVE
      :TIPRECT :TIPFGCOLOR :YHIDDEN :TABSPADDING :TABSIMAGEPOSITION :DRAWSIZE
      :TABSTEXTCLIP :CLOSEIMAGEPRESS :EXTRATIP :TABSTEXTALIGNMENT :EXTRAPRESSCOLOR
	     :FONTFACE :DRAWCOLOR :DRAWTEXTORIENTATION :DRAWBGCOLOR :EXTRAHIGHCOLOR
      :TABORIENTATION :TABSLINECOLOR :NAME :TABSBACKCOLOR :VALUEPOS :BACKINGSTORE
      :DRAWDRIVER :YAUTOHIDE :DRAWSTYLE :TABSALIGNMENT :VALUE :TABIMAGE :ACTIVE
	     :TIPVISIBLE :TABFORECOLOR :EXTRAFONT :YMAX :TABSTEXTORIENTATION
      :EXPANDWEIGHT :MINSIZE :CLOSEHIGHCOLOR :TABFONTSTYLE :CLOSEIMAGE
	     :EXTRAIMAGEINACTIVE :EXTRABUTTONS :BORDER :TABSHIGHCOLOR :CHARSIZE
      :CLIENTSIZE :CLIENTOFFSET :FORECOLOR :DRAGTYPES :EXTRAALIGNMENT :FONTSTYLE
      :TOUCH :TABTITLE :EXTRAIMAGEHIGHLIGHT :XDISPLAY :TABACTIVE :FONT)))) 

|#
